### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by LukasLichten** [PabloMK7/citra#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Restoring the wiki, which contained user as well as developer instructions (including build instructions).  
  
To me there are no known backups of the wiki, but there is archive.org [snapshot](https://web.archive.org/web/20240304191755/https://github.com/citra-emu/citra/wiki) from minutes before it got nuked, which I would be willing to take on to restore into markdown (if no one happens to have the wiki cloned and laying around somewhere).  
  
The original wiki did also contain dumping information, considering the "incident", it might be better to limit the amount of information restored.

### Why would this feature be useful?

Having at least build instructions would be kind of neat

**Comment by PabloMK7** [comment]
Hello, I have no plan to restore the wiki or any instructions yet. Time will tell how things will evolve.

**Comment by TimTheBig** [comment]
[faq_20240304.zip](https://github.com/PabloMK7/citra/files/14501424/faq_20240304.zip)
The wiki from archive.org
