### ISSUE TITLE
Allow screenshot capture when in paused state

### ISSUE THREAD

**Issue by RocketRobz** [PabloMK7/citra#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

The ability to capture a screenshot when the emulator is in a paused state.

### Why would this feature be useful?

The user would examine the screen before taking a screenshot of it. Currently, the emulator would need to be unpaused before taking a screenshot, and the screenshot would slightly differ from the paused state, depending on what's happening on-screen.

**Comment by PabloMK7** [comment]
Hello, this is because the game needs to render a frame for a screenshot to be captured. If you need to capture the current frame use an external tool.

**Comment by RocketRobz** [comment]
Would it not be possible to save the rendered frame on paused state then? Would it require reworking parts of the code to implement that?
