### ISSUE TITLE
Add original issues/PRs?

### ISSUE THREAD

**Issue by mariomadproductions** [PabloMK7/citra#11]
### Issue

If this is going to function as the new repo, that would be a good idea, imo.

**Comment by jonbarrow** [comment]
You can't just bring those things over

The original issues maybe, but each one would have to be remade by hand by someone manually. And depending on how many there are that's likely not feasible

But you definitely can't just bring in the original PRs that easily. Those require code changes, and this is a different codebase. The people who made those PRs would need to redo their changes against this fork and reopen the PRs

**Comment by mariomadproductions** [comment]
Ah I see. If this isn't a mirror from the final commit of the original repo, this issue might not really be relevant.

**Comment by mariomadproductions** [comment]
Although there is an API for creating issues I think.
