### ISSUE TITLE
instant crash when loading any game

### ISSUE THREAD

**Issue by verbes4** [PabloMK7/citra#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

24c6ec5

### Description of Issue

instant crash when loading any game, or when connecting to artic base

### Expected Behavior

citra loads the game and doesnt crash

### Reproduction Steps

open citra
load .3ds file or click file -> connect to artic base, type ip and press ok
citra crashes

### Log File

[citra_log.txt](https://github.com/PabloMK7/citra/files/15287578/citra_log.txt)

### System Configuration

CPU: AMD Custom 0405 (8) @ 2.80 GHz
GPU/Driver: AMD Custom GPU 0405 @ 0.20 GHz [Integrated]
RAM: 16GB
OS: SteamOS Holo 3.5.19 (steamdeck) x86_64, Kernel 6.1.52-valve16-1-neptune-61

**Comment by verbes4** [comment]
https://github.com/PabloMK7/citra/assets/24574201/f489eb1c-7965-489c-a75e-cf7d42b9fc91

**Comment by babtown** [comment]
I have the same issue, here is footage of what happened on the pc and 3ds in real time as well as the citra log
[citra_log.txt](https://github.com/PabloMK7/citra/files/15287686/citra_log.txt)

https://github.com/PabloMK7/citra/assets/30322271/28624af5-cb5e-4a7c-bd68-2fd33e6845f2

**Comment by PabloMK7** [comment]
I cannot reproduce those crashes manually... :/
If anyone is able to compile from source and get the backtrace it would help a lot. Meanwhile I will try to reproduce this myself somehow....

**Comment by JLiveOf** [comment]
the error line appears to be on both logs this

Linux: Debug <Critical> ./core/hle/result.h:operator():367: Assertion Failed!
Tried to Unwrap empty ResultVal

Windows: Debug <Critical> core/hle/result.h:ResultVal<class std::unique_ptr<class FileSys::ArchiveBackend,struct std::default_delete<class FileSys::ArchiveBackend> > >::Unwrap::<lambda_1>::operator ():367: Assertion Failed!
Tried to Unwrap empty ResultVal

**Comment by PabloMK7** [comment]
Yes, I can read that, but that is called from thousands of places in the codebase.

**Comment by verbes4** [comment]
> I cannot reproduce those crashes manually... :/ If anyone is able to compile from source and get the backtrace it would help a lot. Meanwhile I will try to reproduce this myself somehow....

i can try, i know how to compile stuff however ive never needed to get a backtrace before so im unsure on how to do it

**Comment by Pugemon** [comment]
I get an same application crash on an msvc build, but there is no crash on an msys2 build for windows

**Comment by Timbo303** [comment]
I think it might be tied to arctic base implementation or something. The other update works just fine before adding arctic base implementation. I have the same issues.

**Comment by Billybobertjoe** [comment]
It crashes without me even trying arctic base. Just starting a game through Citra itself crashes.

**Comment by Billybobertjoe** [comment]
Also happens on android build, except app doesn't crash, it just goes back to the Citra main menu.

**Comment by algoruin** [comment]
I get the same issue, I tried to compile from the source and get this:
![stack](https://github.com/PabloMK7/citra/assets/9383716/4bfbbef1-6157-4a68-8bd0-6181c68f990b)

Is this what you meant by backtrace?

**Comment by PabloMK7** [comment]
Thank you very much, that's exactly what I needed. :D

**Comment by PabloMK7** [comment]
Please verify that the latest release fixes the issue: https://github.com/PabloMK7/citra/releases/latest

**Comment by verbes4** [comment]
> Please verify that the latest release fixes the issue: https://github.com/PabloMK7/citra/releases/latest

working perfectly now, thanks :)
![Screenshot_20240513_102902-1](https://github.com/PabloMK7/citra/assets/24574201/aa43fefe-f3e1-44af-b1d0-cdc4f0f8fdc9)

**Comment by rvilasecaar** [comment]
> Please verify that the latest release fixes the issue: https://github.com/PabloMK7/citra/releases/latest

I had the same problem as verbes4, and I installed the version you sent of citra and the issue is still happening
