### ISSUE TITLE
Playing Smash with DLC through ArticBase results in Smash with no DLC installed

### ISSUE THREAD

**Issue by fvig2001** [PabloMK7/citra#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

r71eca05

### Description of Issue

New 3DS has Smash with DLC. Playing it through Citra via ArticBase results in the game not having any DLC.

![screen](https://github.com/PabloMK7/citra/assets/31123547/21d579a9-93c0-4685-951e-278693fcfa09)

### Expected Behavior

On Citra, the DLC character is available on screen.

![image](https://github.com/PabloMK7/citra/assets/31123547/86a1a0ac-e45d-4e8b-bb6a-3755b71370da)
Screenshot is from 3DS.

Actual is that the game behaves that there is no DLC installed

### Reproduction Steps

Requirements:

1. New 3DS
2. Smash with character DLC installed

Steps:
1. Run Citra ArticBase build
2. Run ArticBase
3. Run Super Smash Bros.
4. On Citra, connect to ArticBase
5. Go through Smash menus and go to a screen with character select

### Log File

[citra_log.txt](https://github.com/PabloMK7/citra/files/15307926/citra_log.txt)

### System Configuration

CPU: AMD 7800X3D
GPU/Driver: 4080 Super
RAM: 64GB
OS: Win11

**Comment by PabloMK7** [comment]
Hello, please check Artic Base Server Readme:
https://github.com/PabloMK7/ArticBaseServer/blob/main/README.md
