### ISSUE TITLE
Improve Pretendo support

### ISSUE THREAD

**Issue by SuperPat45** [PabloMK7/citra#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Add an option in the web tab to enable online features with Pretendo, like cemu does.
And auto-patch everything on the fly.

### Why would this feature be useful?

Make Pretendo a lot easier to use for customer as it will no more need to manually install patches.

**Comment by PabloMK7** [comment]
Hello, not planned.

**Comment by Anonymous941** [comment]
Why is this not planned?
