### ISSUE TITLE
ñ?

### ISSUE THREAD

**Issue by Linkdash2019** [PabloMK7/citra#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Github

### Description of Issue

Why is the readme and update name/info a simple ñ?

### Expected Behavior

An actual readme and info on updates.

### Reproduction Steps

Open new citra github repository.
Optional open update info

### Log File

N/A

### System Configuration

N/A

**Comment by AmyRoxwell** [comment]
It's a cute letter!

**Comment by BoogieHasFun** [comment]
first of all, ñ

second of all, **probably** for legal reasons. they can't really call it citra or say it's citra otherwise Nintendo will assassinate them

**Comment by MavisCelus19201** [comment]
Might be worth renaming the repo, assuming that's possible.

**Comment by queenbiscuit311** [comment]
ñ

**Comment by PabloMK7** [comment]
ñ

**Comment by dxgldotorg** [comment]
Call it ñata aka piñata!

**Comment by BoogieHasFun** [comment]
> Might be worth renaming the repo, assuming that's possible.

it is possible

**Comment by dxgldotorg** [comment]
> > Might be worth renaming the repo, assuming that's possible.
> 
> it is possible

How do you like my proposal?

**Comment by BoogieHasFun** [comment]
> > > Might be worth renaming the repo, assuming that's possible.
> 
> > 
> 
> > it is possible
> 
> 
> 
> How do you like my proposal?

yes

**Comment by Marvin732** [comment]
can you still use the Online Multiplayer in the latest release?

**Comment by dxgldotorg** [comment]
> can you still use the Online Multiplayer in the latest release?

If it has direct IP you can I believe.  The server browser is dead.
