### ISSUE TITLE
Skip streaming texture if custom texture exists for it

### ISSUE THREAD

**Issue by killersquid1440** [PabloMK7/citra#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Basically, if the texture requested has a custom texture available and custom textures is enabled, it skips streaming that texture and just uses the custom texture instead.

### Why would this feature be useful?

Having this will allow loading times for textures to be decreased if the user has custom textures.

**Comment by PabloMK7** [comment]
Hello, the texture needs to be streamed for many reasons, including the parameters and format. N
