### ISSUE TITLE
Storage Access

### ISSUE THREAD

**Issue by ManyullynSword** [PabloMK7/citra#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Storage Access to install CIA files, like this project github.com/weihuoya/citra. 

### Why would this feature be useful?

It can make the installing process more instant.

**Comment by PabloMK7** [comment]
Hello, not sure what you mean, you can already access storage to install files.

**Comment by ManyullynSword** [comment]
> Hello, not sure what you mean, you can already access storage to install files.
When I install CIA files, Citra will say: xxx.cia must be decrypted before being used with Citra. A real 3DS is requiered.

**Comment by PabloMK7** [comment]
That error is unrelated to storage access. The game dump is encrypted and the keys are not provided.

**Comment by ManyullynSword** [comment]
> That error is unrelated to storage access. The game dump is encrypted and the keys are not provided.该错误与存储访问无关。游戏转储已加密，未提供密钥。

Is it possible to add an access to the Emulator to decrypt the CIA file like that project?

**Comment by Linkdash2019** [comment]
That would open the doors wide to piracy. I would assume no.
