### ISSUE TITLE
aes_keys.txt not working with citra on macOS 14.5 and build  tag rde1f082   version de1f082 

### ISSUE THREAD

**Issue by gh0sti** [PabloMK7/citra#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

de1f082

### Description of Issue

Citra for some reason is having issues reading the aes_keys.txt I have provided.

### Expected Behavior

citra should be able to decrypt encrypted cia files using aes_keys

### Reproduction Steps

add aes_keys.txt to sysdata under application support on macos

### Log File

I have included screenshots of the error along with setup of sysdata folder.
<img width="498" alt="citra 1" src="https://github.com/PabloMK7/citra/assets/4202657/ddab420f-3122-42b8-9a19-97aa03bb17f4">
<img width="613" alt="citra 2" src="https://github.com/PabloMK7/citra/assets/4202657/b088cf1c-4383-4c3b-a49a-6f64a442cb23">
<img width="799" alt="citra 3" src="https://github.com/PabloMK7/citra/assets/4202657/9dc4754e-544d-4a99-9f01-1c57f6e3affe">
[citra_log.txt](https://github.com/user-attachments/files/15541423/citra_log.txt)

### System Configuration

CPU: Apple M2
GPU/Driver: Apple M2
RAM: 8GB
OS: macOS 14.5

**Comment by PabloMK7** [comment]
Hello, looks like that game is pirated, cannot give support sorry.

**Comment by gh0sti** [comment]
> Hello, looks like you have pirated games, cannot give support sorry.

1st I'm not asking for support on a specific game. I am asking why is citra not able to read my aes_keys?

2nd you have no proof that the games I have are "pirated". They are my personal backups.

**Comment by Linkdash2019** [comment]
Just wondering but why can’t you just decrypt the game with your 3ds? After decryption the CIA’s can be installed just fine.
