### ISSUE TITLE
Latest Mac Download Fails

### ISSUE THREAD

**Issue by naevist** [PabloMK7/citra#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

rde1f082

### Description of Issue

when downloading the latest version of Citra on Mac from https://citra-emulator.com/download/mac/ it sends me to a new page saying the site can't be reached

### Expected Behavior

when clicking the download button it should just start downloading the emulator without error

### Reproduction Steps

going to https://citra-emulator.com/download/mac/ and clicking download on the latest citra for mac

### Log File

<img width="1440" alt="Screen Shot 2024-06-06 at 12 29 33 AM" src="https://github.com/PabloMK7/citra/assets/171897198/1f47671f-716a-4039-acd2-d26cf8e72e27">

### System Configuration

CPU: 1.6 GHz Dual-Core Intel Core i5
GPU/Driver: Intel UHD Graphics 617 1536 MB
RAM: 8 GB
OS: macOS 11.7

**Comment by PabloMK7** [comment]
Hello, this project is unrelated to that website.

**Comment by naevist** [comment]
oh for some reason it sends me to this site? my apologies
