### ISSUE TITLE
Fatal Error Occured ( after enabling LLE modules for Online )

### ISSUE THREAD

**Issue by Phenix54s** [PabloMK7/citra#15]
This happens after enabling required LLE modules changes : 
![image](https://github.com/PabloMK7/citra/assets/19185182/183e6143-159a-420b-8fda-20c9c320d9e9)

trying to continue provide no online of course 
( all files have properly been dumped right during tutorial , and boot after LLE modules is where it fails

this was tried starting from a clean emulator   without junk files anywhere

[citra_log.txt](https://github.com/PabloMK7/citra/files/13994533/citra_log.txt)

( sent here as tutorials says so )

**Comment by Fuadevil007** [comment]
disable LLE ACT

**Comment by PabloMK7** [comment]
You forgot to do the part of the guide that tells to re-do the "Download system titles from Nintendo servers". In particular, you need to download New 3DS titles **AND** Old 3DS titles.
