### ISSUE TITLE
zip and 7zip files for linux and windows builds do not appear to work properly on linux

### ISSUE THREAD

**Issue by queenbiscuit311** [PabloMK7/citra#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

v2.1, v.2.2

### Description of Issue

I noticed that I can open and use this fork on macos and windows, but trying to extract any of these files on linux makes a weird or corrupted extraction. this, as far as i can tell, doesnt happen at all with the normal version of the nondescript fruit-based emulation program. i've tried multiple archive management programs with the same result.

Example 1:
![image](https://github.com/PabloMK7/citra/assets/88851292/c433b60d-aa65-4b3a-b0e1-a67e1a5b57ea)

opening windows release zip file on linux leads to weird messed up directory structure. if fixed manually the files themselves are fine, but the files instead are all in one folder with their relative paths as filenames. as you can see this doesn't happen on 7-zip running via wine.

Example 2:

![image](https://github.com/PabloMK7/citra/assets/88851292/0551938b-2783-489c-88af-207f691c255d)

Linux appimage build extracted with windows 7zip (left) works as expected. Appimage extracted with linux archive manager (right) has corrupted appimage files that do not open.

### Expected Behavior

zip files extract properly regardless of operating system

### Reproduction Steps

1. open and extract release archive for windows or linux on linux
2. theyre messed up

### Log File

N/A

### System Configuration

CPU:N/A
GPU/Driver:N/A
RAM:N/A
OS: Arch Linux x86_64

**Comment by BoogieHasFun** [comment]
for linux, only the citra-qt appimage runs. not trying windows as microsoft stinky

**Comment by queenbiscuit311** [comment]
> for linux, only the citra-qt appimage runs. not trying windows as microsoft stinky (also be prepared to be blinded upon opening citra)

for me that appimage doesnt work for whatever reason unless i use windows 7zip. both citra and citra-qt images are corrupted. which program are you using to extract?

**Comment by queenbiscuit311** [comment]
should note that if i use 7zip to extract and then re-compress the files into the same type of archive it works fine on linux

**Comment by BoogieHasFun** [comment]
i am using the linux mint archive manager, nothing special

**Comment by queenbiscuit311** [comment]
i'll try that one, so far no dice with dolphin, ark, or gnome archive manager.

**Comment by BoogieHasFun** [comment]
otherwise known as https://gitlab.gnome.org/GNOME/file-roller (be prepared to be blinded again)

**Comment by queenbiscuit311** [comment]
oh well file roller is what im using. im going to try on a mint live iso and see if it still does this

**Comment by BoogieHasFun** [comment]
try running the appimage through the terminal, it may give you some sort of log

**Comment by queenbiscuit311** [comment]
for a more scientific approach, here's the checksums im getting for the same file via 7-zip and linux archive manager
![image](https://github.com/PabloMK7/citra/assets/88851292/6bd1d536-6da4-44ea-bbd5-e01cf2e8488b)

**Comment by BoogieHasFun** [comment]
i dunno how to help you buddy, this is weird. the checksum of the working file does match mine, though

**Comment by queenbiscuit311** [comment]
I see. can't tell if this is an issue with this repository, a github issue, or somehow something wrong with some program or library on arch.

**Comment by BoogieHasFun** [comment]
i think it has to be an issue with arch, and i cannot help with arch because i have no knowledge of how to use arch. sorry :(

**Comment by queenbiscuit311** [comment]
Okay, so after more testing, the appimage thing appears to specifically be an issue with dolphin file manager's built-in 7zip archive support. ive never had issues with it before but apparently it just is not to be trusted and ill just use 7-zip or ark instead. as for the windows zip file issue, that is still a problem regardless of my file manager, however since the amount of people trying to extract windows binaries on a linux machine is probably very low its definitely not important, so i will close this issue.
