### ISSUE TITLE
no vulkan device on arch

### ISSUE THREAD

**Issue by qqlow** [PabloMK7/citra#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

all

### Description of Issue

citra cannot find vulkan device on arch, using mesa git, latest appimage, log is empty
vulkan is working in every other app

### Expected Behavior

can use vulkan

### Reproduction Steps

open citra, error popup will open

### Log File

empty

### System Configuration

CPU: 6800u
GPU/Driver: 680m
RAM: 32
OS: arch

**Comment by 46620** [comment]
I get the same issue using the appimage or AUR package, but compiling it the issue doesn't seem to happen.

CPU: 5900x
GPU: 7900xtx
RAM: 32GB
OS: Arch

**Comment by guilty-p01nt3r** [comment]
Same here.
Works with other apps.

OS: Arch Linux x86_64
Kernel: 6.9.4-zen1-1-zen 
CPU: AMD Ryzen 5 3600 (12) @ 4.125GHz 
GPU: AMD ATI Radeon RX 7900 XT

![image](https://github.com/PabloMK7/citra/assets/31125013/f31fe835-c157-4dfb-afc7-bd57d0549b54)

**Comment by DonKatsu** [comment]
Not sure when it started for me, but I;m getting it as well. Tried starting the 20240406-0c2f076 appimage one day and got the Vulkan initialization failed message. Same with 20240717-518f723.

OS: CachyOS
Kernel: 6.10.0
CPU: 5900X
GPU: 6700 XT
Mesa: 24.1.4 stable

**Comment by PabloMK7** [comment]
Hello, can you test with the app images from here: https://github.com/PabloMK7/citra/actions/runs/10406563510

**Comment by 46620** [comment]
same issue

![image](https://github.com/user-attachments/assets/29b014b0-06c8-4d5a-be2b-7b3cca0129f6)
[citra_log.txt](https://github.com/user-attachments/files/16636927/citra_log.txt)

**Comment by DonKatsu** [comment]
> Hello, can you test with the app images from here: https://github.com/PabloMK7/citra/actions/runs/10406563510

Still no go here as well. Same log output as the previous reply. mesa 24.2.0.
![image](https://github.com/user-attachments/assets/2d0b4165-688c-47a9-9ab1-f5f2b4dd2198)
Vulkan does initialize with compiled Citra for me as well.

**Comment by PabloMK7** [comment]
What about this? @DonKatsu @46620 
https://github.com/PabloMK7/citra/actions/runs/10473846656/artifacts/1833003885

**Comment by 46620** [comment]
> What about this? @DonKatsu @46620 https://github.com/PabloMK7/citra/actions/runs/10473846656/artifacts/1833003885

Works/10, no warning on start and games load
