### ISSUE TITLE
How to set up Friend Codes?

### ISSUE THREAD

**Issue by Mae-Kappa** [PabloMK7/citra#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Citra F4174f1

### Description of Issue

Found a post describing the same issue I'm having- friend code generates blank. Saw the response as follows "That's not relevant, I can confirm with an older Citra version of this fork I can succesfully download system files, enable all LLE modules needed (including http) and after making a mii the friend code will indeed be generated"
The problem is I am INCREDIBLY new to this... HOW do i enable these "LLE modules" including HTTP? I've set up the home menu and made a mii, not sure if I'm missing any system files... all that seems to remain is LLE and HTTP... I know this isn't a bug report persay but if literally anyone can help, please do. I've been scouring the internet for hours looking for answers.

### Expected Behavior

Friend code properly generating

### Reproduction Steps

Boot USA Home Menu. Open Friends List. See Friend Code generating as ????-????-????

### Log File

since citra shut down the link to how to upload the log file doesn't work :(

### System Configuration

CPU: AMD Ryzen 7 2700X Eight-Core Processor
GPU/Driver: Radeon RX Vega 64
RAM: 16GB
OS: Windows 11

**Comment by PabloMK7** [comment]
Hello, the LLE modules list is in view -> debugging -> toggle lle modules.
From there you can turn on the appropriate modules (remember to not enable http for now).

Closing as it's not an issue

**Comment by Mae-Kappa** [comment]
@PabloMK7 Thank you for your help thus far! The problem still is I do not know _which_ LLE modules I need to enable for it to generate a friend code. Only enabling FRD (which I can assume means FRIEND) now shows my mii, it's name, and I can now set a status message, but my friend code is still not generating.

**Comment by Linkdash2019** [comment]
SSl, ACT FRD are the ones I have enabled. But I do use an outdated version of citra for online play (Citra 1af7235 to be exact)

**Comment by squarepizza1** [comment]
I'm still having this issue. I don't know if it will ever be fixed. It doesn't what modules I have on. My friend code refuses to generate as something that isn't just ????-????-????

**Comment by custrtrs** [comment]
> I'm still having this issue. I really hope it gets fixed. It doesn't matter what modules I have on, my friend code refuses to generate as something that isn't just ????-????-????

Try loading LocalFriendCodeSeed_A/B. You need to download it from somewhere though.

**Comment by squarepizza1** [comment]
I have loaded it. I've already redumped my online files several times, so It can't be a bad dump.
