### ISSUE TITLE
Arch Linux package build fail

### ISSUE THREAD

**Issue by T0x1cL** [PabloMK7/citra#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

This affects building rather than a specific build.

### Description of Issue

I was trying to build `citra-git` based off of [this PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=citra-git) and ran into these issues:

1. [/externals/ext-boost](https://github.com/PabloMK7/ext-boost/tree/3c27c785ad0f8a742af02e620dc225673f3a12d8) points to a commit not in any branch of the repository. This causes a `git unload-pack` error when trying to `git submodule update`.
2. After using a hack (local commit to update the targeted commit or something along the lines of that, I don't really have a clear idea of what I'm doing) to get past that, returns a `no such file or directory` error when trying to configure zycore submodule of  dynarmic submodule (I think that's what it's trying to do?)
3. After commenting that entire block out, I get a bunch of CMake errors at externals/CMakeLists.txt because the directories do not contain a CMakeLists.txt file (upon inspection, they seem to be empty)

I'll come back with updates to issues 2 and 3 if/when 1 is fixed (There was a similar issue on the Yuzu mirror, those were fixed and the PKGBUILD built successfully)

### Expected Behavior

Package builds (`citra-$pkgver.pkg.tar.zst is created).

### Reproduction Steps

 [PKGBUILD.txt](https://github.com/PabloMK7/citra/files/14504052/PKGBUILD.txt)
Attached is the PKGBUILD I'm using.

1. have an Arch Linux (or derivative) distribution ready to build AUR packages (requires `base-devel` package)
2. download above PKGBUILD, run `makepkg -s` for `1.`, then uncomment lines 120-121 for `2.`, then comment lines 137-140 for `3.`

### Log File

1. [log_1.txt](https://github.com/PabloMK7/citra/files/14504069/log_1.txt)
2. [log_2.txt](https://github.com/PabloMK7/citra/files/14504070/log_2.txt)
3. [log_3.txt](https://github.com/PabloMK7/citra/files/14504071/log_3.txt)

### System Configuration

CPU: Ryzen 7 5800X
GPU/Driver: RX 6700 XT (amdgpu)
RAM: 16 GiB
OS: Artix Linux

**Comment by queenbiscuit311** [comment]
I haven't tried it in a pkgbuild but i built using [the instructions from the now-removed wiki](https://archive.org/download/yuzu-citra-source-code-binaries/Citra%20Source%20Code%20Building%20Instructions/Building%20for%20Windows%20%C2%B7%20citra-emu_citra%20Wiki%20%C2%B7%20GitHub.pdf)  on arch and it worked first try.

**Comment by Miguel-hrvs** [comment]
Compile it with git clone and git submodule update --init --recursive. The only thing is that my binaries weigh 10mb more than Pablo's ones.

**Comment by PabloMK7** [comment]
Indeed the repo was missing the commit, fixed it

**Comment by T0x1cL** [comment]
Manual building (though on a laptop running Mint because I'm not at home) seems to run, but tests fail.
[LastTest.log](https://github.com/PabloMK7/citra/files/14508801/LastTest.log)
Something similar seems to have been mentioned in the [AUR package page](https://web.archive.org/web/20240228004049/https://aur.archlinux.org/packages/citra-git).

@queenbiscuit311 The PKGBUILD seems to clone all the repositories for the submodules then configures their urls in the citra repo to point to the local clone. (I was using an edited version of the PKGBUILD linked in the Building for Linux guide)

I'll muck around with the PKGBUILD when I get back and have access to my Artix machine.

**Comment by queenbiscuit311** [comment]
i can see if the tests for my builds pass or fail as well

**Comment by queenbiscuit311** [comment]
So I tried the PKGBUILD you sent with no modification whatsoever and it built first try with no issues.

**Comment by T0x1cL** [comment]
I tried it myself and it builds; the issues 2 and 3 were probably the issues of me not building it properly (I don't really know how to bring the repo to a specific commit). Tests pass with DSP stuff skipped, log [attached](https://github.com/PabloMK7/citra/files/14514563/LastTest.log)

I'll try faffing around with PKGBUILDs and manual building to see if it can build with the version number. If I get it to work, I'll post it here.

Thanks!
