### ISSUE TITLE
MH4U graphical issues while upscaling after coming back of a quest online.

### ISSUE THREAD

**Issue by AmyRoxwell** [PabloMK7/citra#16]
Version used: v2.0 of this fork
Drivers: Mesa drivers version 23.3.3
GPU: RX6600
CPU: Ryzen 5 5600
Upscaling: affects all upscale levels.

While going after a quest, sometimes the textures will glitch out until you go back into a quest again.
This doesn't seem to happen on native and it gets fixed by going from your upscale level to native and going back to your desire upscale level
![Screenshot_01212024_171755](https://github.com/PabloMK7/citra/assets/89411895/4ccf4f58-c061-489a-a816-98d4bc3ae8bb)
![Screenshot_01212024_171720](https://github.com/PabloMK7/citra/assets/89411895/2d6b1762-1d38-4acb-bca5-11322875d0d7)![Screenshot_01212024_171818](https://github.com/PabloMK7/citra/assets/89411895/75e1ab74-07b6-4f41-92f0-e47ef9d19894)

**Comment by PabloMK7** [comment]
Hello, I'm closing this as it's unrelated to online features. It's better to report in the official citra repository.

**Comment by AmyRoxwell** [comment]
Here the issue, this only happens on online play, and due to that, I cant report it on the official repo :b
