### ISSUE TITLE
Softlock at Home Menu Booting

### ISSUE THREAD

**Issue by NovaKitty15** [PabloMK7/citra#17]
After booting the home menu, it loads into the Initial Setup and asks me to move the 3d depth slider which doesn't work. So it's impossible to actually boot into the home menu.

![Screenshot 2024-01-28 185428](https://github.com/PabloMK7/citra/assets/157983676/520a4464-a857-4289-8785-ab327dfd6025)

**Comment by PabloMK7** [comment]
Hello, this is an issue regarding official citra, so it's not the right place to report it here.

In any case, move the 3D slider up in Emulation settings.
