### ISSUE TITLE
Errors when updating the android app

### ISSUE THREAD

**Issue by Starlightbotanist** [PabloMK7/citra#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All (confirmed issue is still present on r4780a71)

### Description of Issue

When updating the app on android, there is a package conflict error, requiring the app to be uninstalled/reinstalled with every update. I am not a developer, but I believe this issue is related to package signing.

Issue has been present since the first and second release of the PabloMK7 builds.

### Expected Behavior

App would be able to be updated without uninstalling/reinstalling.

### Reproduction Steps

Install any older build ([r4f174f1](https://github.com/PabloMK7/citra/releases/tag/r4f174f1) for example), then try updating to [r4780a71](https://github.com/PabloMK7/citra/releases/tag/r4780a71).

### Log File

I do not know how to produce a log file for this exact issue. However, I am able to reproduce it on 4 different android devices.

### System Configuration

CPU: SD8g2
GPU/Driver: stock
RAM: 12gb
OS: android 13

I have also reproduced this issue on an android 12 and android 14 device.

**Comment by PabloMK7** [comment]
Hello, thanks for the report, but there are no plans to sign the package.
