### ISSUE TITLE
FIre Emblem Fates: Special Edition immediately crashes through Arctic Base on latest version.

### ISSUE THREAD

**Issue by graceluca** [PabloMK7/citra#178]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

r4780a71

### Description of Issue

When I try to load Fire Emblem Fates: Special Edition, specifically 0004000000179800, through Arctic Base, Citra will say that the game is loading, show a black screen for a few seconds, then give a fatal error. If I click continue it will continue to hang on the black screen. This is different from #90 because it does not even get to the point of showing any classes, and happens through Arctic Base.

https://github.com/user-attachments/assets/7673ce26-dd47-423b-8d55-df23916e79d0

### Expected Behavior

The game is playable.

### Reproduction Steps

1. Open Artic Base on 3DS.
2. Open Fire Emblem Fates: Special Edition (0004000000179800) on 3DS.
3. Connect to Citra with Arctic Base.

### Log File

[citra_log.txt.old.txt](https://github.com/user-attachments/files/16185296/citra_log.txt.old.txt)

### System Configuration

CPU: AMD Ryzen 5 5600X 6-Core Processor
GPU/Driver: NVIDIA GeForce RTX 3060 Ti
RAM: 32gb DDR4
OS: Windows 11

**Comment by PabloMK7** [comment]
Enable the debug log on the 3DS side by pressing X before connecting to citra. Send screenshot of the log just after the game gets the critical error.

**Comment by graceluca** [comment]
The video is everything up until critical error. The photo is the log right after it happens. 
![PXL_20240712_1500197442 1](https://github.com/user-attachments/assets/d9487943-6695-42a0-8e90-ae08fef9fd1b)
https://github.com/user-attachments/assets/350bdb86-f68d-49ec-9021-df5fe7a6f99e
