### ISSUE TITLE
Remove "shaderSampledImageArrayDynamicIndex" for Raspberry Pi 4/5

### ISSUE THREAD

**Issue by Lolothepro** [PabloMK7/citra#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Remove "shaderSampledImageArrayDynamicIndex" for Raspberry Pi 4/5

### Why would this feature be useful?

Raspberry Pi 4/5 support

**Comment by PabloMK7** [comment]
Is this a vulkan incompatibility?

**Comment by Lolothepro** [comment]
Raspberry Pi not compatible with it in v3dv

**Comment by Lolothepro** [comment]
See https://gitlab.freedesktop.org/mesa/mesa/-/issues/9713

**Comment by Lolothepro** [comment]
Note: https://github.com/PabloMK7/citra/commit/20ef8e47e6f92c0225208c57b9c1114741612e77
