### ISSUE TITLE
[Android] Receiving error code 018-0201 upon entering a town from acnl or join a match in smash bros

### ISSUE THREAD

**Issue by duynamDJ** [PabloMK7/citra#18]
I can connect to nintendo server, i can add friend, but I can't enter a match in smash bros or join a faraway town from acnl with the error code being 018-0201

**Comment by duynamDJ** [comment]
![Uploading Screenshot_20240130-001929.png…]()

**Comment by PabloMK7** [comment]
As noted in the release notes, Android does not work currently.
