### ISSUE TITLE
Jogos do mario crashando

### ISSUE THREAD

**Issue by Gilyusuke** [PabloMK7/citra#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

e90795b

### Description of Issue

Usando api vulkan o jogos da franquia mario nao abre ele crasha antes de chegar no menu inicial

### Expected Behavior

Outras versoes o emulador entrava mas aparti da adicao do articbase  ele parou de executar

### Reproduction Steps

[   2.551089] Frontend <Error> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_error:23: [FileUtil]: Cannot open content uri, error: Failed to determine if primary:Download/3ds/0005_Super_Mario_3D_Land_Europe_En,Fr,De,Es,It,Nl,Pt,Ru_Decrypted.3ds.exheader is child of primary:Download/3ds: java.io.FileNotFoundException: Missing file for primary:Download/3ds/0005_Super_Mario_3D_Land_Europe_En,Fr,De,Es,It,Nl,Pt,Ru_Decrypted.3ds.exheader at /storage/emulated/0/Download/3ds/0005_Super_Mario_3D_Land_Europe_En,Fr,De,Es,It,Nl,Pt,Ru_Decrypted.3ds.exheader
[   2.564403] Frontend <Info> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_info:19: [FileUtil] Cannot find file from given path, error: Failed to determine if primary:Download/3ds/0005_Super_Mario_3D_Land_Europe_En,Fr,De,Es,It,Nl,Pt,Ru_Decrypted.3ds.romfs is child of primary:Download/3ds: java.io.FileNotFoundException: Missing file for primary:Download/3ds/0005_Super_Mario_3D_Land_Europe_En,Fr,De,Es,It,Nl,Pt,Ru_Decrypted.3ds.romfs at /storage/emulated/0/Download/3ds/0005_Super_Mario_3D_Land_Europe_En,Fr,De,Es,It,Nl,Pt,Ru_Decrypted.3ds.romfs
[   2.567871] Frontend <Info> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_info:19: [FileUtil] Cannot find file from given path, error: Failed to determine if primary:Download/3ds/0005_Super_Mario_3D_Land_Europe_En,Fr,De,Es,It,Nl,Pt,Ru_Decrypted.3ds.exefs is child of primary:Download/3ds: java.io.FileNotFoundException: Missing file for primary:Download/3ds/0005_Super_Mario_3D_Land_Europe_En,Fr,De,Es,It,Nl,Pt,Ru_Decrypted.3ds.exefs at /storage/emulated/0/Download/3ds/0005_Super_Mario_3D_Land_Europe_En,Fr,De,Es,It,Nl,Pt,Ru_Decrypted.3ds.exefs
[   2.570778] Frontend <Info> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_info:19: [FileUtil] Cannot find file from given path, error: Failed to determine if primary:Download/3ds/0005_Super_Mario_3D_Land_Europe_En,Fr,De,Es,It,Nl,Pt,Ru_Decrypted.3ds.exefsdir is child of primary:Download/3ds: java.io.FileNotFoundException: Missing file for primary:Download/3ds/0005_Super_Mario_3D_Land_Europe_En,Fr,De,Es,It,Nl,Pt,Ru_Decrypted.3ds.exefsdir at /storage/emulated/0/Download/3ds/0005_Super_Mario_3D_Land_Europe_En,Fr,De,Es,It,Nl,Pt,Ru_Decrypted.3ds.exefsdir
[   2.573187] Frontend <Error> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_error:23: [FileUtil]: Cannot open content uri, error: Failed to determine if primary:Download/3ds/0005_Super_Mario_3D_Land_Europe_En,Fr,De,Es,It,Nl,Pt,Ru_Decrypted.3ds.exefsdir is child of primary:Download/3ds: java.io.FileNotFoundException: Missing file for primary:Download/3ds/0005_Super_Mario_3D_Land_Europe_En,Fr,De,Es,It,Nl,Pt,Ru_Decrypted.3ds.exefsdir at /storage/emulated/0/Download/3ds/0005_Super_Mario_3D_Land_Europe_En,Fr,De,Es,It,Nl,Pt,Ru_Decrypted.3ds.exefsdir
[   2.596171] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   2.619311] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384

### Log File

Sansung a31 

### System Configuration

CPU:8
GPU/Driver:mali
RAM:4
OS:

**Comment by PabloMK7** [comment]
Hello, looks like you are using a pirated copy of the game. Therefore, I cannot help you, sorry.

**Comment by Gilyusuke** [comment]
Bom amigo estou tendo apenas problemas apos adicao da articbase antes rodava muito bem e sao todos os jogos do mario , como mario kart e luigis e todos outros jogos estao rodando bem vou lhe mandar o arquivo completo para ver mas 
[citra_log.txt.old.txt](https://github.com/user-attachments/files/16203507/citra_log.txt.old.txt)
