### ISSUE TITLE
the eshop always telling me that i have to update despite me downloading the latest version

### ISSUE THREAD

**Issue by dsmirc** [PabloMK7/citra#19]
I have done everything as the guide instructs, yet, for some unknown reason, this issue still persists. 

I have also dumped everything correctly Even CTCert.bin (for some reason it shows that it's invalid but I have dumped it correctly from a real n3ds)

**Comment by dsmirc** [comment]
I can still play online games such as super mario maker and kart 7

**Comment by PabloMK7** [comment]
The eshop does not work without eshop save data dumped from a real console, as mentioned in the releases page.
