### ISSUE TITLE
Android upgrade error

### ISSUE THREAD

**Issue by ItachiSan** [PabloMK7/citra#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All builds after r4780a71, I believe

### Description of Issue

Updating version on Android is not possible due to a "conflict error".
This happens via helpers such as Obtanium and by the normal APK download & install.

### Expected Behavior

I expect to be able to install version N and later install version N+1.

### Reproduction Steps

With N being the number of the latest release:
1. Install release N-1 cleanly
2. Try installing release N

### Log File

None to mention

### System Configuration

CPU: Not relevant
GPU/Driver: Not relevant
RAM: 8GB
OS: Android 14

**Comment by PabloMK7** [comment]
This is normal Android behavior, the APK is not signed so you need to uninstall the previous version and install the new one.

**Comment by ItachiSan** [comment]
May I ask why before the issue was not happening though?
It is  bit annoying having to redo the setup process every time.
It is still good that almost all the settings are saved in the Citra folder.

**Comment by foolishgrunt** [comment]
Though it seems like the decision has been made (which I'll try to respect), I'll second the opinion that the process of manually uninstalling before each upgrade is obnoxious. And it's not like there's 6 months between releases, either.
