### ISSUE TITLE
Infinite loading and or/ Fatal error popups

### ISSUE THREAD

**Issue by Phenix54s** [PabloMK7/citra#21]
For some reason ,  i have hard issue booting some games 
( mainly  pokemon ultrasun/moon )

they usually don't start and throw a fata error  when booting , or when installed from their CIA , and booter from home menu , they both  just  stay stuck in the 3ds game boot animation  forever 

wich is kinda strange, as the said games start an run perfectly fine on normal Citra emulator but not on this version ( 2.1 of online fork  here ) 
[citra_log.txt](https://github.com/PabloMK7/citra/files/14254893/citra_log.txt)

**Comment by Phenix54s** [comment]
forgot to mention , some games does NOT boot when  not installed too, but does boot fine when loaded from home menu ( pokemon X , pokemon Bank ( wich has another issue but i tried  by curiosity )  etc

**Comment by PabloMK7** [comment]
Please install New 3DS titles AND Old 3DS titles from Nintendo CDN as mentioned in the instructions. You are missing Old 3DS titles.
