### ISSUE TITLE
can't get friend code

### ISSUE THREAD

**Issue by Deka710** [PabloMK7/citra#22]
after created my own Mii then go to friend list i can't get the friend code (????????) and the name says Citra.
![Screenshot_2024-02-13-11-27-37-843_org citra citra_emu](https://github.com/PabloMK7/citra/assets/97207704/aea424fb-6753-40a2-9095-ead08f1d543b)

**Comment by Deka710** [comment]
[citra_log.txt](https://github.com/PabloMK7/citra/files/14256595/citra_log.txt)
[citra_log.txt.old.txt](https://github.com/PabloMK7/citra/files/14256597/citra_log.txt.old.txt)

**Comment by Deka710** [comment]
ok fixed the name
![Screenshot_2024-02-13-12-27-42-844_org citra citra_emu](https://github.com/PabloMK7/citra/assets/97207704/e222c2fb-6027-4902-b572-d56ffc46b876)
here the log:
[citra_log.txt](https://github.com/PabloMK7/citra/files/14256634/citra_log.txt)
[citra_log.txt.old.txt](https://github.com/PabloMK7/citra/files/14256636/citra_log.txt.old.txt)

**Comment by PabloMK7** [comment]
You forgot to enable the lle system modules, please read the instructions again.

**Comment by Deka710** [comment]
> You forgot to enable the lle system modules, please read the instructions again.

![Screenshot_2024-02-27-07-10-30-651_ru zdevs zarchiver](https://github.com/PabloMK7/citra/assets/97207704/9f76f855-8b40-48d0-823f-959814b28db1)
i already did? maybe im doing it wrong?
