### ISSUE TITLE
8bitdo Pro 2 controller X Y button mapping in Android

### ISSUE THREAD

**Issue by SilverGreen93** [PabloMK7/citra#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

20240717-518f723

### Description of Issue

Using Cirta on Android 14. When mapping controller buttons in the Gamepad settings, buttons X and Y appear as Virtual: Button 67 and Virtual: Button 62 instead of 8BitDo Pro 2: Button, as all other buttons do.
This makes the X and Y buttons unusable. They do not work in the game.
Note that the controller works fine with all the other emulators.

### Expected Behavior

The buttons should map as 8BitDo Pro 2: Button, just like all other buttons.

### Reproduction Steps

Map buttons on 8BitDo Pro 2 controller.
See that only X and Y show as Virtual buttons.

### Log File

[citra_log.txt](https://github.com/user-attachments/files/16451487/citra_log.txt)

### System Configuration

Xiaomi 13T running Android 14

**Comment by PabloMK7** [comment]
Hello, by looking at the logs looks like you are using a pirated game. Therefore I'll have to close this issue, sorry.
