### ISSUE TITLE
Bootntr support

### ISSUE THREAD

**Issue by Priestyle** [PabloMK7/citra#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Can citra support bootntr?

### Why would this feature be useful?

This feature would add to the list of many features available on the citra emulator and this feature would mean more accurate emulatoin of the 3ds and ultimately, it’ll be more fun for the users.

**Comment by PabloMK7** [comment]
Hello, there are no plans for bootntr support as it's not possible with the emu being HLE
