### ISSUE TITLE
Citra Crashes with Vulkan API - Backtrace Provided

### ISSUE THREAD

**Issue by JAcob37269** [PabloMK7/citra#233]
### Issue

Description:
I am experiencing a crash when using Citra with the Vulkan API. The application quits immediately after opening a game, and no error message is displayed. I have generated a backtrace using GDB, and I'm providing it below for further investigation.

System Specifications:
- CPU: AMD A10-7850K
- GPU: NVIDIA GeForce GT 730 (2GB DDR5)
- RAM: 8GB
- Storage: WD Blue 500GB HDD
- Operating System: Windows 10 (64-bit)

Steps to Reproduce:
1. Launch Citra.
2. Configure the graphics settings to use Vulkan API.
3. Open any game.
4. Observe that Citra crashes immediately with no error message.

Backtrace:
```
0x00007ff96115ba99 in RaiseException () from C:\Windows\System32\KernelBase.dll
#0  0x00007ff96115ba99 in RaiseException () from C:\Windows\System32\KernelBase.dll
#1  0x00007ff948f46ba7 in _CxxThrowException () from C:\Windows\SYSTEM32\vcruntime140.dll
#2  0x00007ff763dbbf3b in citra-qt!?is_destroyed@?$singleton@V?$map@Vbinary_oarchive@archive@boost@@@extra_detail@detail@archive@boost@@@serialization@boost@@SA_NXZ ()
#3  0x00007ff763dbaf5d in citra-qt!?is_destroyed@?$singleton@V?$map@Vbinary_oarchive@archive@boost@@@extra_detail@detail@archive@boost@@@serialization@boost@@SA_NXZ ()
#4  0x00007ff763709dd1 in citra-qt!?save_object_data@?$oserializer@Vbinary_oarchive@archive@boost@@VPicaCore@Pica@@@detail@archive@boost@@UEBAXAEAVbasic_oarchive@234@PEBX@Z ()
#5  0x00007ff76370f1cc in citra-qt!?save_object_data@?$oserializer@Vbinary_oarchive@archive@boost@@VPicaCore@Pica@@@detail@archive@boost@@UEBAXAEAVbasic_oarchive@234@PEBX@Z ()
#6  0x00007ff7637146c0 in citra-qt!?save_object_data@?$oserializer@Vbinary_oarchive@archive@boost@@VPicaCore@Pica@@@detail@archive@boost@@UEBAXAEAVbasic_oarchive@234@PEBX@Z ()
#7  0x00007ff763710877 in citra-qt!?save_object_data@?$oserializer@Vbinary_oarchive@archive@boost@@VPicaCore@Pica@@@detail@archive@boost@@UEBAXAEAVbasic_oarchive@234@PEBX@Z ()
#8  0x00007ff763758b50 in citra-qt!?save_object_ptr@?$pointer_oserializer@Vbinary_oarchive@archive@boost@@VGeometryPipeline_VariablePrimitive@Pica@@@detail@archive@boost@@EEBAXAEAVbasic_oarchive@234@PEBX@Z ()
#9  0x00007ff76374cff4 in citra-qt!?save_object_ptr@?$pointer_oserializer@Vbinary_oarchive@archive@boost@@VGeometryPipeline_VariablePrimitive@Pica@@@detail@archive@boost@@EEBAXAEAVbasic_oarchive@234@PEBX@Z ()
#10 0x00007ff7636f9556 in citra-qt!??0?$oserializer@Vbinary_oarchive@archive@boost@@VPicaCore@Pica@@@detail@archive@boost@@QEAA@XZ ()
#11 0x00007ff7636f9319 in citra-qt!??0?$oserializer@Vbinary_oarchive@archive@boost@@VPicaCore@Pica@@@detail@archive@boost@@QEAA@XZ ()
#12 0x00007ff763367345 in citra-qt!??0?$oserializer@Vbinary_oarchive@archive@boost@@VTiming@Core@@@detail@archive@boost@@QEAA@XZ ()
```

Additional Information:
- I have tried running the game with the OpenGL API, and it works without crashing.
- The Vulkan API option causes the crash consistently.

Logs:
- No additional logs are available as the application quits immediately without displaying any error message.

Suggestions:
- Could this issue be related to Vulkan API compatibility or configuration?

**Comment by rharish101** [comment]
Have you tried manually setting your Vulkan device (your GPU in this case) in the Graphics options? I experienced a similar crash until I did so.

**Comment by davidbepo** [comment]
> Have you tried manually setting your Vulkan device (your GPU in this case) in the Graphics options? I experienced a similar crash until I did so.

huh, that works

**Comment by Gamer64ytb** [comment]
Should be fixed on https://github.com/PabloMK7/citra/actions/runs/10545459796 build.
