### ISSUE TITLE
Rename your fork to distinguish it from the old one and update the links in the About window.

### ISSUE THREAD

**Issue by hazem-abdelghani** [PabloMK7/citra#240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Renaming the fork to unique name such as Citra MK7.

### Why would this feature be useful?

Rename your fork to distinguish it from the old one.

**Comment by PabloMK7** [comment]
Hello, thank you but this is not planned yet.
