### ISSUE TITLE
Professor Layton and the Legacy of the Ashalanti crash

### ISSUE THREAD

**Issue by Shadowdark44** [PabloMK7/citra#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

5115f64

### Description of Issue

The game Professor Layton and the Legacy of the Ashalanti It crashes when you enter the game, more specifically the emulator crashes

### Expected Behavior

After the dialogues shown in the video, a puzzle minigame should start. 

### Reproduction Steps

https://github.com/user-attachments/assets/79ae6fe0-9ad3-4e18-8e34-fda5ef22a34c

### Log File

[   0.000198] Frontend <Info> main/jni/native.cpp:Java_org_citra_citra_1emu_NativeLibrary_createLogFile:590: Logging backend initialised
[   0.000298] Frontend <Info> main/jni/native.cpp:Java_org_citra_citra_1emu_NativeLibrary_logUserDirectory:597: User directory path: content://com.android.externalstorage.documents/tree/primary%3Aarchivos%2FGames%2Fcitra%F0%9F%8D%8A
[   0.035723] Config <Info> main/jni/config.cpp:LoadINI:57: Successfully loaded /config/config.ini
[   0.077297] Frontend <Info> main/jni/native.cpp:Java_org_citra_citra_1emu_NativeLibrary_logDeviceInfo:743: Citra Version: 5115f64 | HEAD-5115f64
[   0.077576] Frontend <Info> main/jni/native.cpp:Java_org_citra_citra_1emu_NativeLibrary_logDeviceInfo:744: Host CPU: Unisoc T606
[   0.077601] Frontend <Info> main/jni/native.cpp:Java_org_citra_citra_1emu_NativeLibrary_logDeviceInfo:746: Host OS: Android API level 31
[   0.077701] Frontend <Info> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_info:19: Device Manufacturer - TECNO
[   0.077725] Frontend <Info> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_info:19: Device Model - TECNO KI5k
[   0.077756] Frontend <Info> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_info:19: SoC Manufacturer - Spreadtrum
[   0.077782] Frontend <Info> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_info:19: SoC Model - T606
[   0.078528] Frontend <Info> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_info:19: Total System Memory - 8.0 GB
[   0.403246] HW.AES <Error> core/hw/aes/key.cpp:LoadPresetKeys:227: Failed to parse 
[   0.403425] HW.AES <Error> core/hw/aes/key.cpp:LoadPresetKeys:227: Failed to parse 
[   0.403427] HW.AES <Error> core/hw/aes/key.cpp:LoadPresetKeys:227: Failed to parse 
[   0.403494] HW.AES <Error> core/hw/aes/key.cpp:LoadPresetKeys:227: Failed to parse 
[   0.403497] HW.AES <Error> core/hw/aes/key.cpp:LoadPresetKeys:227: Failed to parse 
[   0.403508] HW.AES <Error> core/hw/aes/key.cpp:LoadPresetKeys:227: Failed to parse 
[   0.403511] HW.AES <Error> core/hw/aes/key.cpp:LoadPresetKeys:227: Failed to parse 
[   0.403543] HW.AES <Error> core/hw/aes/key.cpp:LoadPresetKeys:227: Failed to parse 
[   0.403545] HW.AES <Error> core/hw/aes/key.cpp:LoadPresetKeys:227: Failed to parse 
[   0.403572] HW.AES <Error> core/hw/aes/key.cpp:LoadPresetKeys:227: Failed to parse 
[   0.403575] HW.AES <Error> core/hw/aes/key.cpp:LoadPresetKeys:227: Failed to parse 
[   0.403744] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:344: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[   0.430441] Frontend <Error> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_error:23: [FileUtil]: Cannot open content uri, error: Failed to determine if 0000-0000:Archivos/citra🍊/Monster Hunter 4Ultimate.cxi.exheader is child of 0000-0000:Archivos/citra🍊: java.io.FileNotFoundException: Missing file for 0000-0000:Archivos/citra🍊/Monster Hunter 4Ultimate.cxi.exheader at /storage/0000-0000/Archivos/citra🍊/Monster Hunter 4Ultimate.cxi.exheader
[   0.454271] Frontend <Info> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_info:19: [FileUtil] Cannot find file from given path, error: Failed to determine if 0000-0000:Archivos/citra🍊/Monster Hunter 4Ultimate.cxi.romfs is child of 0000-0000:Archivos/citra🍊: java.io.FileNotFoundException: Missing file for 0000-0000:Archivos/citra🍊/Monster Hunter 4Ultimate.cxi.romfs at /storage/0000-0000/Archivos/citra🍊/Monster Hunter 4Ultimate.cxi.romfs
[   0.458620] Frontend <Info> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_info:19: [FileUtil] Cannot find file from given path, error: Failed to determine if 0000-0000:Archivos/citra🍊/Monster Hunter 4Ultimate.cxi.exefs is child of 0000-0000:Archivos/citra🍊: java.io.FileNotFoundException: Missing file for 0000-0000:Archivos/citra🍊/Monster Hunter 4Ultimate.cxi.exefs at /storage/0000-0000/Archivos/citra🍊/Monster Hunter 4Ultimate.cxi.exefs
[   0.462322] Frontend <Info> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_info:19: [FileUtil] Cannot find file from given path, error: Failed to determine if 0000-0000:Archivos/citra🍊/Monster Hunter 4Ultimate.cxi.exefsdir is child of 0000-0000:Archivos/citra🍊: java.io.FileNotFoundException: Missing file for 0000-0000:Archivos/citra🍊/Monster Hunter 4Ultimate.cxi.exefsdir at /storage/0000-0000/Archivos/citra🍊/Monster Hunter 4Ultimate.cxi.exefsdir
[   0.465970] Frontend <Error> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_error:23: [FileUtil]: Cannot open content uri, error: Failed to determine if 0000-0000:Archivos/citra🍊/Monster Hunter 4Ultimate.cxi.exefsdir is child of 0000-0000:Archivos/citra🍊: java.io.FileNotFoundException: Missing file for 0000-0000:Archivos/citra🍊/Monster Hunter 4Ultimate.cxi.exefsdir at /storage/0000-0000/Archivos/citra🍊/Monster Hunter 4Ultimate.cxi.exefsdir
[   1.004984] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   1.010863] Frontend <Error> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_error:23: [FileUtil]: Cannot open content uri, error: Failed to determine if 0000-0000:Archivos/citra🍊/Monster Hunter 3 Ultimate (USA) (En,Fr,De,Es,It).3ds.exheader is child of 0000-0000:Archivos/citra🍊: java.io.FileNotFoundException: Missing file for 0000-0000:Archivos/citra🍊/Monster Hunter 3 Ultimate (USA) (En,Fr,De,Es,It).3ds.exheader at /storage/0000-0000/Archivos/citra🍊/Monster Hunter 3 Ultimate (USA) (En,Fr,De,Es,It).3ds.exheader
[   1.043066] Frontend <Info> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_info:19: [FileUtil] Cannot find file from given path, error: Failed to determine if 0000-0000:Archivos/citra🍊/Monster Hunter 3 Ultimate (USA) (En,Fr,De,Es,It).3ds.romfs is child of 0000-0000:Archivos/citra🍊: java.io.FileNotFoundException: Missing file for 0000-0000:Archivos/citra🍊/Monster Hunter 3 Ultimate (USA) (En,Fr,De,Es,It).3ds.romfs at /storage/0000-0000/Archivos/citra🍊/Monster Hunter 3 Ultimate (USA) (En,Fr,De,Es,It).3ds.romfs
[   1.050158] Frontend <Info> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_info:19: [FileUtil] Cannot find file from given path, error: Failed to determine if 0000-0000:Archivos/citra🍊/Monster Hunter 3 Ultimate (USA) (En,Fr,De,Es,It).3ds.exefs is child of 0000-0000:Archivos/citra🍊: java.io.FileNotFoundException: Missing file for 0000-0000:Archivos/citra🍊/Monster Hunter 3 Ultimate (USA) (En,Fr,De,Es,It).3ds.exefs at /storage/0000-0000/Archivos/citra🍊/Monster Hunter 3 Ultimate (USA) (En,Fr,De,Es,It).3ds.exefs
[   1.056161] Frontend <Info> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_info:19: [FileUtil] Cannot find file from given path, error: Failed to determine if 0000-0000:Archivos/citra🍊/Monster Hunter 3 Ultimate (USA) (En,Fr,De,Es,It).3ds.exefsdir is child of 0000-0000:Archivos/citra🍊: java.io.FileNotFoundException: Missing file for 0000-0000:Archivos/citra🍊/Monster Hunter 3 Ultimate (USA) (En,Fr,De,Es,It).3ds.exefsdir at /storage/0000-0000/Archivos/citra🍊/Monster Hunter 3 Ultimate (USA) (En,Fr,De,Es,It).3ds.exefsdir
[   1.061435] Frontend <Error> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_error:23: [FileUtil]: Cannot open content uri, error: Failed to determine if 0000-0000:Archivos/citra🍊/Monster Hunter 3 Ultimate (USA) (En,Fr,De,Es,It).3ds.exefsdir is child of 0000-0000:Archivos/citra🍊: java.io.FileNotFoundException: Missing file for 0000-0000:Archivos/citra🍊/Monster Hunter 3 Ultimate (USA) (En,Fr,De,Es,It).3ds.exefsdir at /storage/0000-0000/Archivos/citra🍊/Monster Hunter 3 Ultimate (USA) (En,Fr,De,Es,It).3ds.exefsdir
[   1.110326] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   1.172072] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   1.305092] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   1.310524] Frontend <Error> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_error:23: [FileUtil]: Cannot open content uri, error: Failed to determine if 0000-0000:Archivos/citra🍊/El Profesor Layton y El Legado de Los Ashalanti [N3DS] [Roms en Espanol].3ds.exheader is child of 0000-0000:Archivos/citra🍊: java.io.FileNotFoundException: Missing file for 0000-0000:Archivos/citra🍊/El Profesor Layton y El Legado de Los Ashalanti [N3DS] [Roms en Espanol].3ds.exheader at /storage/0000-0000/Archivos/citra🍊/El Profesor Layton y El Legado de Los Ashalanti [N3DS] [Roms en Espanol].3ds.exheader
[   1.349945] Frontend <Info> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_info:19: [FileUtil] Cannot find file from given path, error: Failed to determine if 0000-0000:Archivos/citra🍊/El Profesor Layton y El Legado de Los Ashalanti [N3DS] [Roms en Espanol].3ds.romfs is child of 0000-0000:Archivos/citra🍊: java.io.FileNotFoundException: Missing file for 0000-0000:Archivos/citra🍊/El Profesor Layton y El Legado de Los Ashalanti [N3DS] [Roms en Espanol].3ds.romfs at /storage/0000-0000/Archivos/citra🍊/El Profesor Layton y El Legado de Los Ashalanti [N3DS] [Roms en Espanol].3ds.romfs
[   1.356982] Frontend <Info> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_info:19: [FileUtil] Cannot find file from given path, error: Failed to determine if 0000-0000:Archivos/citra🍊/El Profesor Layton y El Legado de Los Ashalanti [N3DS] [Roms en Espanol].3ds.exefs is child of 0000-0000:Archivos/citra🍊: java.io.FileNotFoundException: Missing file for 0000-0000:Archivos/citra🍊/El Profesor Layton y El Legado de Los Ashalanti [N3DS] [Roms en Espanol].3ds.exefs at /storage/0000-0000/Archivos/citra🍊/El Profesor Layton y El Legado de Los Ashalanti [N3DS] [Roms en Espanol].3ds.exefs
[   1.365751] Frontend <Info> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_info:19: [FileUtil] Cannot find file from given path, error: Failed to determine if 0000-0000:Archivos/citra🍊/El Profesor Layton y El Legado de Los Ashalanti [N3DS] [Roms en Espanol].3ds.exefsdir is child of 0000-0000:Archivos/citra🍊: java.io.FileNotFoundException: Missing file for 0000-0000:Archivos/citra🍊/El Profesor Layton y El Legado de Los Ashalanti [N3DS] [Roms en Espanol].3ds.exefsdir at /storage/0000-0000/Archivos/citra🍊/El Profesor Layton y El Legado de Los Ashalanti [N3DS] [Roms en Espanol].3ds.exefsdir
[   1.371914] Frontend <Error> main/jni/native_log.cpp:Java_org_citra_citra_1emu_utils_Log_error:23: [FileUtil]: Cannot open content uri, error: Failed to determine if 0000-0000:Archivos/citra🍊/El Profesor Layton y El Legado de Los Ashalanti [N3DS] [Roms en Espanol].3ds.exefsdir is child of 0000-0000:Archivos/citra🍊: java.io.FileNotFoundException: Missing file for 0000-0000:Archivos/citra🍊/El Profesor Layton y El Legado de Los Ashalanti [N3DS] [Roms en Espanol].3ds.exefsdir at /storage/0000-0000/Archivos/citra🍊/El Profesor Layton y El Legado de Los Ashalanti [N3DS] [Roms en Espanol].3ds.exefsdir
[   1.443984] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   1.524452] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384

### System Configuration

Android 12 
8 gb ram

**Comment by Shadowdark44** [comment]
[citra_log.txt](https://github.com/user-attachments/files/16731023/citra_log.txt)


This is the complete log, sorry XD

**Comment by PabloMK7** [comment]
Probably it doesn't help that you have an emoji in the Citra path lol

Anyways, you seem to be using a pirated game, and we won't give any assistance with that, sorry.
