### ISSUE TITLE
Request: Publish this on Google Play Store

### ISSUE THREAD

**Issue by WindowsNinetyTen** [PabloMK7/citra#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Is it possible to make this be available on the Google Play Store?

### Why would this feature be useful?

It would make the emulator installable without having to allow apps from unknown sources, and the Google Play Store is the most secure way to install apps.

**Comment by PabloMK7** [comment]
Hello, thanks for the suggestion, but there are no plans to do that currently.
