### ISSUE TITLE
Citra does not connect to Arctic base via Ethernet on PC

### ISSUE THREAD

**Issue by Megaloading** [PabloMK7/citra#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All builds

### Description of Issue

When i try to connect to Arctic base it only outputs that an error has occured
I have tried using a Wi-Fi dongle and to my surprise that worked, however i do not have a good dongle nor a good connection in my room so i would like to use Ethernet.

![Screenshot (18)](https://github.com/user-attachments/assets/d21bdfa1-c0b2-41eb-bdfb-f16fd353f0d9)

### Expected Behavior

I don't know if it should do this however it works with a Wi-Fi dongle

### Reproduction Steps

Download the latest release of citra to your PC and Arctic base on the 3DS, then connect to the internet using Ethernet and launch Arctic base on the 3DS, connect to Arctic base with the ip address and wait.

### Log File

[citra_log.txt](https://github.com/user-attachments/files/16802852/citra_log.txt)

### System Configuration

CPU: Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz   3.60 GHz
GPU/Driver: Nvidia GeForce RTX 2060
RAM: 16,0 GB
OS: Windows 11 64-bit

**Comment by PabloMK7** [comment]
Hello, whether your computer is connected through Ethernet or wifi is indifferent to citra. There is probably a network issue on your end when using Ethernet, or the devices end up in different networks.

Closing as it's not an issue on Citra.

**Comment by Megaloading** [comment]
Ok, thank you, i will look further unto this issue👍.
