### ISSUE TITLE
Booting .firm files?

### ISSUE THREAD

**Issue by pbz134** [PabloMK7/citra#246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

A way to boot .firm files, such as gm9 and other payloads.

### Why would this feature be useful?

Exploring and experimenting with the 3DS file system, extracting system files, emulating another part of the real console.

**Comment by PabloMK7** [comment]
Hello, citra is a high level emulator, so loading firm files will never work.
