### ISSUE TITLE
Artic Base stream save data only

### ISSUE THREAD

**Issue by Hario337** [PabloMK7/citra#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Using Artic base to stream your save data from a 3DS, but running the game from a dump instead.

### Why would this feature be useful?

This would allow for one to play their 3DS saves on Citra seamlessly without having to manually dump them back and forth, while still ensuring smooth performance and minimal load times. This would just require the user to dump their game beforehand.

(I would also like to suggest an alternative solution of having streamed game data be stored on your computer even after closing the game, that way assets don't have to be streamed again every time you reboot, but that feels more complex and less viable)

**Comment by PabloMK7** [comment]
Hello, that feature is outside the scope of the tool, sorry.
