### ISSUE TITLE
Retroarch Citra Non-existent on Nintendo Switch version.

### ISSUE THREAD

**Issue by Impulse706** [PabloMK7/citra#267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Latest

### Description of Issue

.CXI files aren't seen by the application on Homebrewed Switch.

### Expected Behavior

The app should find the correct file and directory.

### Reproduction Steps

Drop in CXI, look for it.

### Log File

N/A

### System Configuration

CPU: ARM
GPU/Driver: ARM
RAM: 4GB
OS: Atmosphere

**Comment by PabloMK7** [comment]
Hello! 
Sorry, but this version of citra does not support the switch, you should ask the author of the fork that added support for it
