### ISSUE TITLE
MH4U crashes on launching online

### ISSUE THREAD

**Issue by cself99** [PabloMK7/citra#3]
Log: https://pastebin.com/GLzi17c4

When trying to launch online multiplayer MH4U instantly crashes. MHGen works fine though I'm not sure this is relevant.

**Comment by agent13** [comment]
Same here. DLC quests download works normal.
One thing: MH4 connect without issues.

**Comment by PabloMK7** [comment]
Coul you try without JIT enabled? (Emulation -> Configure -> General -> Debug)
It will make the game run slow, but need to check if it's an issue related to JIT.

**Comment by cself99** [comment]
I can't seem to get the game to load at all with JIT disabled.

Log: https://pastebin.com/Km06gg43

**Comment by GPUCode** [comment]
Can you post a save file alongside reproduction steps to get the crash?

**Comment by cself99** [comment]
https://drive.google.com/file/d/1GtvUzBAFNHMj72V-lCakrdoelOaztFVE/view?usp=sharing

All you need to do is load either file, click "World Map" in the bottom right of the touch screen, click "Solo/Multiplayer" at the top, then click Online Multiplayer and when it starts to load it'll crash. This is on v1.1 of the game also in case that matters.

**Comment by cself99** [comment]
Looks like this is fixed on the latest commit. Thanks!
