### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by luc-git** [PabloMK7/citra#31]
### Issue

Original citra installer doesn't seems to be open source and is not recovered. So why not implement an open source one in this repo

**Comment by Linkdash2019** [comment]
I believe with the original citra installer you can redirect the update site to a different repo… so maybe the original can still be used. The only problem is when I add this repo the updater is unable to read update.xml* (I am going off of memory for the file name.)

**Comment by luc-git** [comment]
> I believe with the original citra installer you can redirect the update site to a different repo… so maybe the original can still be used. The only problem is when I add this repo the updater is unable to read update.xml* (I am going off of memory for the file name.)

I tried and I doesn't work for me and it's not a good idea to add an executable on github

**Comment by PabloMK7** [comment]
There are no plans to make an installer as of now.

**Comment by PabloMK7** [comment]
There are no plans to make an installer as of now.
