### ISSUE TITLE
Weird visual issue in Pokémon Ultra Sun/Moon

### ISSUE THREAD

**Issue by LOuroboros** [PabloMK7/citra#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

8433057

### Description of Issue

This is an issue that has existed in Citra for years. I verified that it's still happening in this fork, and decided to open an issue ticket for it.

It happens with all 3 graphics backends; Vulkan, OGL and even Software.

Ancient Poni Path:

![citra-qt_20240312_074203089](https://github.com/PabloMK7/citra/assets/4485172/c11a5b8a-ec35-492e-b39d-cee8e22d1ee6)

Route 9:

![citra-qt_20240312_075456404](https://github.com/PabloMK7/citra/assets/4485172/63b7e81c-a180-40b7-8441-cca0ae123c93)
![citra-qt_20240312_080033387](https://github.com/PabloMK7/citra/assets/4485172/8bd47190-cd37-4d79-b309-0b440785f540)

### Expected Behavior

https://youtu.be/oH-1ahAsGxQ?t=18700

![firefox_20240312_084109155](https://github.com/PabloMK7/citra/assets/4485172/803c4fa7-a59d-4640-a05a-1e94e11e8f5d)

https://youtu.be/oH-1ahAsGxQ?t=36818

![firefox_20240312_084331381](https://github.com/PabloMK7/citra/assets/4485172/18ed28df-9dc5-402a-b9a4-a3e0256370ea)

### Reproduction Steps

Simply walk into those areas and check the spots showed in the pictures above.

### Log File

[citra_log.txt](https://github.com/PabloMK7/citra/files/14571611/citra_log.txt)

### System Configuration

**CPU**: i3 2120
**GPU/Driver**: GIGABYTE's NVIDIA GeForce GT 1030, Driver Version 551.52
**RAM**: 4 GB DDR3, single channel because reasons.
**OS**: Windows 11 v22H2 x64, Build Number 22621.2283

**Comment by Lolothepro** [comment]
duplicate of https://github.com/PabloMK7/citra/issues/29

**Comment by Miguel-hrvs** [comment]
I imagine that you have the async graphic options disabled

**Comment by LOuroboros** [comment]
> duplicate of #29

Sorry, my bad. I did check that Issue ticket but I didn't look at the video properly. I'll close this one.

> I imagine that you have the async graphic options disabled

I only have Async Presentation disabled, fwiw.

I'll move my pictures and videos to the other ticket.
