### ISSUE TITLE
Replacing « How to get keys? » links

### ISSUE THREAD

**Issue by mickbot-92** [PabloMK7/citra#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

It would be useful to replace https://citra-emu.org/wiki/aes-keys/ with for example https://github.com/PabloMK7/citra/tree/master/dist/dumpkeys :)

### Why would this feature be useful?

The former link won't work, that's why…

**Comment by askotx** [comment]
Just with info like this was some of the reasons Yuzu had legal issues: Showing to user to get keys.

**Comment by Miguel-hrvs** [comment]
Please, close this issue, we are not going to make guides about keys stuff.

**Comment by mickbot-92** [comment]
Okay, I understand 👍
