### ISSUE TITLE
Build issue with LLVM 18.1.1 on msys2

### ISSUE THREAD

**Issue by rtiangha** [PabloMK7/citra#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

HEAD

### Description of Issue

Building Citra with Clang 18.1.1 on msys2 now yields this error:

```
In file included from C:/msys64/home/Default/github/bravely-offline-citra/src/citra_qt/util/graphics_device_info.cpp:5:
In file included from C:/msys64/home/Default/github/bravely-offline-citra/src/./citra_qt/util/graphics_device_info.h:8:
In file included from C:/msys64/clang64/include/qt6/QtCore/QString:1:
In file included from C:/msys64/clang64/include/qt6/QtCore/qstring.h:14:
In file included from C:/msys64/clang64/include/qt6/QtCore/qchar.h:656:
In file included from C:/msys64/clang64/include/qt6/QtCore/qstringview.h:8:
In file included from C:/msys64/clang64/include/qt6/QtCore/qbytearray.h:14:
C:/msys64/clang64/include/qt6/QtCore/qbytearrayview.h:69:27: error: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t i
s non-standard and is provided for a temporary period. It will be removed in LLVM 19, so please migrate off of it. [-Werror,-Wdeprecated-declarations]
   69 |     return qsizetype(std::char_traits<Char>::length(data));
      |                           ^
C:/msys64/clang64/include/qt6/QtCore/qbytearrayview.h:151:39: note: in instantiation of function template specialization 'QtPrivate::lengthHelperPointer<unsigned char>' requested here
  151 |               data, data ? QtPrivate::lengthHelperPointer(data) : 0) {}
      |                                       ^
C:/msys64/home/Default/github/bravely-offline-citra/src/citra_qt/util/graphics_device_info.cpp:25:34: note: in instantiation of function template specialization 'QByteArrayView::QByteArrayView
<const unsigned char *, true>' requested here
   25 |         return QString::fromUtf8(context.functions()->glGetString(GL_RENDERER));
      |                                  ^
C:/msys64/clang64/include/c++/v1/__string/char_traits.h:81:8: note: 'char_traits<unsigned char>' has been explicitly marked deprecated here
   81 | struct _LIBCPP_DEPRECATED_(
      |        ^
C:/msys64/clang64/include/c++/v1/__config:975:53: note: expanded from macro '_LIBCPP_DEPRECATED_'
  975 | #      define _LIBCPP_DEPRECATED_(m) __attribute__((__deprecated__(m)))
      |                                                     ^
1 error generated.
ninja: build stopped: subcommand failed.
```
And the compiler seems to now be enforcing this deprecation.

I'm not a strong coder, but I was able to get something that compiled with the assistance of Copilot AI, but it breaks Vulkan (so more investigation needed, but I get better performance on OpenGL on this set up anyway so I can live with it).

That said, as far as I can tell, _at least_ these files need to be modified:

```
src/citra_qt/main.cpp
src/citra_qt/util/graphics_device_info.cpp
src/citra_qt/util/graphics_device_info.h
```

to rework the QString stuff. I'm not very familiar with the code to know if there are other places as well.

### Expected Behavior

Successful compilation.

### Reproduction Steps

Build Citra with Clang 18.1.1 (on msys2, but maybe on other OSes as well).

### Log File

No logs; this is a compile issue.

### System Configuration

CPU: Intel Kaby Lake
GPU/Driver: Integrated Intel HD Graphics 620
RAM: 8GB
OS: Windows 10 64-bit

**Comment by Miguel-hrvs** [comment]
These guys had the same problem: https://github.com/jtv/libpqxx/issues/738

**Comment by Miguel-hrvs** [comment]
You could try modifying the C:/msys64/clang64/include/qt6/QtCore/qbytearrayview.h file this way:
replace the line 69 with this: return qsizetype(uchar_traits::length(reinterpret_cast<const char*>(data)));
And include this before template <typename Char>:
struct uchar_traits : std::char_traits<char> {
    static void assign(char& r, const char& a) {
        r = a;
    }

    static bool eq(const char& c1, const char& c2) {
        return c1 == c2;
    }

    static bool lt(const char& c1, const char& c2) {
        return c1 < c2;
    }

    static int compare(const char* s1, const char* s2, size_t n) {
        while (n-- != 0) {
            if (*s1 < *s2) return -1;
            if (*s1 > *s2) return 1;
            ++s1; ++s2;
        }
        return 0;
    }

    static const char* find(const char* s, int n, const char& a) {
        auto const ua(a);
        while (n-- != 0) {
            if (*s == ua) return s;
            s++;
        }
        return nullptr;
    }

    static char* move(char* s1, const char* s2, int n) {
        return (char*)memmove(s1, s2, n);
    }

    static char* copy(char* s1, const char* s2, int n) {
        return (char*)memcpy(s1, s2, n);
    }

    static char* assign(char* s, int n, char a) {
        return (char*)memset(s, a, n);
    }

    static char to_char_type(const char& c) {
        return c;
    }

    static char to_int_type(const char& c) {
        return c;
    }

    static bool eq_int_type(const char& c1, const char& c2) {
        return c1 == c2;
    }

    static char eof() {
        return EOF;
    }

    static char not_eof(const char& c) {
        return !(eq_int_type(c, eof())) ? c : 0;
    }
};

**Comment by Miguel-hrvs** [comment]
I just tested the fix and is working great

**Comment by Miguel-hrvs** [comment]
my problem was using old dll libraries. Both methods seem to work.
