### ISSUE TITLE
friends list will not show me as online and restricts my online usage

### ISSUE THREAD

**Issue by MPS64** [PabloMK7/citra#4]
Log: https://pastebin.com/ertgKjnT
whenever I boot up the friends list, it says that my online service access is restricted. do i get a new friend code or will it be completely different? (im using my 3ds nand if thats an issue)
![image_2023-11-02_195300870](https://github.com/PabloMK7/citra/assets/69330570/deeddfec-1bd2-4e79-85da-cb136e0ae745)

**Comment by snoandpetals** [comment]
Close your emulator, go to your 3DS, and check for the same thing. 002-0121 is a ban code, so if it shows up on your actual 3DS you're pretty much screwed. If it shows up on just your emulator, it's probably a bug and I don't know why it's happening.

**Comment by PabloMK7** [comment]
There is nothing wrong in the logs, check that you don't get the same error on 3DS (probably not). If that's the case, dump the console unique data again with godmode9, as it might have got corrupted.

Note: The ban message is misleading, it doesn't mean you are banned, it means the provided console unique data cannot be validated.

**Comment by snoandpetals** [comment]
Apologies, I only knew that code as being a ban code :(
Good to know it most likely just means invalidation somewhere

**Comment by PabloMK7** [comment]
> i have a similar issue except it isnt a ban code, instead i can only be seen as online in the emulator as long as im in the friends list or else i appear offline, no error codes or anything

That's exactly how it should work.

**Comment by PabloMK7** [comment]
Closing as the op doesn't respond
