### ISSUE TITLE
Pretendo support?

### ISSUE THREAD

**Issue by Anonymous941** [PabloMK7/citra#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Now that experimental online support has been added, is it possible to allow connecting to Pretendo?

### Why would this feature be useful?

This would allow online play after the Nintendo wireless connections close, not come with a ban risk, and be better legally as Pretendo is an open source project.  It would also allow playing games with a real 3DS, without forcing you to use Nintendo's servers

**Comment by PabloMK7** [comment]
Yes, it is possible to connect to pretendo by using their account manager and placing the IPS files in the right places.

**Comment by Anonymous941** [comment]
This is very exciting, thank you!

**Comment by Anonymous941** [comment]
I'm having trouble doing this.  I can put the `/luma/titles/*` folders in `citra-emu/load/mods`, but `/luma/sysmodules/*.ips` doesn't seem to have any equivalent I can find.  Also, (and this might be by design), their account manager won't run because it expects a Luma3DS environment, which can't happen due to no ARM9 support

Am I missing something?

**Comment by Anonymous941** [comment]
How do you get online in the first place?  I've dumped my console unique data, loaded it into Citra, but the System Settings just hangs when trying to sign in to a NNID.  I have a feeling I need to enable it somewhere, but I just don't see anything, and can't find any guides online or in the issues

**Comment by Linkdash2019** [comment]
It’s explained on https://web.archive.org/web/20240304191503/https://github.com/PabloMK7/citra/releases
When this project was renamed ñ the change log and tutorial were remived…

**Comment by Anonymous941** [comment]
@Linkdash2019 Thanks, it works now for Nintendo Network.  I can't connect to Pretendo still however - the account manager won't run because it requires Luma3DS, and I don't know where to put the `/luma/sysmodules/*.ips` files

Also, why was the project renamed ñ?  And why is the README blank?

**Comment by TwistedTempest** [comment]
> @Linkdash2019 Thanks, it works now for Nintendo Network. I can't connect to Pretendo still however - the account manager won't run because it requires Luma3DS, and I don't know where to put the `/luma/sysmodules/*.ips` files
Can vouch with the same experience. Placing all Luma files in the emulated sdmc/luma folder as well as the juxt file in /3ds
didn't work. My guess is there's another file path that would work or that a patch for Nimbus needs to be made for it to accept the emulated environment

> Also, why was the project renamed ñ? And why is the README blank?
Probably in the interest of flying under the radar until the dust settles, given what happened to the former main repo

**Comment by Anonymous941** [comment]
> Can vouch with the same experience. Placing all Luma files in the emulated sdmc/luma folder as well as the juxt file in /3ds didn't work. My guess is there's another file path that would work or that a patch for Nimbus needs to be made for it to accept the emulated environment

That's right, the `sdmc/luma` folder isn't used for patches.  I'm not sure where exactly to put these as they are not standard game patches, @PabloMK7 do you know where?  If I know the file paths, I can try to patch Nimbus to work, but it would be hard since Citra doesn't give NAND access to .3dsx files

**Comment by Linkdash2019** [comment]
Well I found another roadblock for pretendo on ñ. Nimbus expects Luma 13 and if luma isn’t found the app will refuse to function. Unless we can trick that app into thinking luma is there or the app looks for citra we can’t use the account manager.

**Comment by TwistedTempest** [comment]
> Well I found another roadblock for pretendo on ñ. Nimbus expects Luma 13 and if luma isn’t found the app will refuse to function. Unless we can trick that app into thinking luma is there or the app looks for citra we can’t use the account manager.

This was already the accepted consensus, so the main goal was to copy the network files from a real 3DS and put them in what PabloMK7 called “the right places.” The issue is that there's no specification on where that is

**Comment by Anonymous941** [comment]
> Well I found another roadblock for pretendo on ñ. Nimbus expects Luma 13 and if luma isn’t found the app will refuse to function. Unless we can trick that app into thinking luma is there or the app looks for citra we can’t use the account manager.

The problem is that Citra (and its forks) don't allow access to NAND.  So it's easy to bypass that check but the app would be useless as it can only read from the SD card...

**Comment by TwistedTempest** [comment]
> The problem is that Citra (and its forks) don't allow access to NAND. So it's easy to bypass that check but the app would be useless as it can only read from the SD card...

If the flags that distinguish between network environments (the unused "dev" ones that Pretendo relies on) are stored in NAND then that might make it impossible to use Pretendo on emulator. It's already impossible to link a NNID to Citra, probably for that reason, so this might still need work

**Comment by Anonymous941** [comment]
> If the flags that distinguish between network environments (the unused "dev" ones that Pretendo relies on) are stored in NAND then that might make it impossible to use Pretendo on emulator. It's already impossible to link a NNID to Citra, probably for that reason, so this might still need work

While 3DS apps can't access the NAND, isn't it still accessible in `citra-emu/nand`?  Also somehow it can download `.cxi` modules (used for connecting to Nintendo Network), but I don't know where they are stored or how to patch them

**Comment by TwistedTempest** [comment]
> While 3DS apps can't access the NAND, isn't it still accessible in `citra-emu/nand`? Also somehow Citra downloads `.cxi` modules (used for connecting to Nintendo Network), but I don't know where they're stored or how to patch them

Right, that could be the case. While I generally understand how these systems work I don't actually know how to code or the full file structure of Citra, so I'm not of much help here

**Comment by Anonymous941** [comment]
> Right, that could be the case. While I generally understand how these systems work I don't actually know how to code or the full file structure of Citra, so I'm not of much help here

Same here, I only know that much after hours of frustration trying to make a program read from NAND, only to find it working on a real 3DS

**Comment by TwistedTempest** [comment]
Update - making some headwind when it comes to connecting. It seems like some have gotten online on Android, but the real trouble is with Windows. Using all 6 LLE modules required for online (ACT, BOSS, FRD, NIM, HTTP, and SSL) at once when the IPS patches for Pretendo are in place causes the emulator to freeze up when trying to access the friend menu. Might open an issue about it

**Comment by Anonymous941** [comment]
@TwistedTempest I'm on Linux, but I don't know where to put the IPS patches to test this.  Should they just be in the normal locations?

**Comment by TwistedTempest** [comment]
1. Download Nimbus 1.6.0
2. Drop the folders from "(nimbus.zip)/luma/titles" into "(Citra)/user/load/mods" as-is.
3. Make new folders in that mods folder with titles corresponding to those in "(nimbus.zip)/luma/sysmodules" (example: 0004013000002E02)
4. Drop the corresponding IPS files into their new title folders, and rename them to code.ips (so that they look the same as those from the titles folder
5. Once you're done, you should have 8 or 9 folders made, each with a 16-character title containing a code.ips file
