### ISSUE TITLE
[Android] Rotating the screen from portrait to landscape crashes the app.

### ISSUE THREAD

**Issue by stepsy** [PabloMK7/citra#55]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

https://github.com/PabloMK7/citra/commit/775ceac27d32a49b9cc333aeb8a588c15010ebf0

### Description of Issue

Exactly what is typed on the title.
This has been an issue on Citra for months.
@GPUCode I'm putting this issue here. So people don't make it again.

### Expected Behavior

Rotating the screen shouldn't crash the app.

### Reproduction Steps

Rotate the screen 3 to 10 times from landscape to portrait and portrait to landscape.
It's kinda random when it'll crash.

### Log File

A log file is not needed.

### System Configuration

Snapdragon 680
Adreno 610
Android 12

**Comment by PabloMK7** [comment]
I think I've had this happen to me too

**Comment by JaffaCat** [comment]
Happens to me too, tested using Samsung Galaxy S23 on Super Mario 3D Land while using Vulkan.

**Comment by GPUCode** [comment]
This is hard issue to solve but can reproduce it as well. During rotation a surface recreation is triggered by android and there is a delicate interaction where that is forwarded to the presentation window and it has to properly synchronize when to recreate the swapchain. I'll see if I can figure out what race condition still exists
