### ISSUE TITLE
Request - Add HOME button - Android [1.0]

### ISSUE THREAD

**Issue by 2020loryx** [PabloMK7/citra#6]
Hi,
I tried your citra app for android (v.1.0), I was very satisfied with it.  While I was doing some experiments with the app I noticed that by installing the system files (dumped from my 3ds) and launching the HOME menu, I could use the emulator like a real 3ds without switching to one app at a time.  So I thought you could create a HOME menu button so that the emulator can be used like a real 3ds.  However, to launch the HOME menu I had to select the game folder as: /citra-emu/nand/0000000000000000000000000000000/title/00040030/00009802/content/;  and select the title that appears "primary%3Acitra-emu%2Fnand...".  This is because the title called HOME menu was not working.  Therefore, I was hoping that you could make this title easier to access in some way. That's all. Thanks for the great work you've done, keep it up.

**Comment by Rix565** [comment]
this is more of a citra issue than a pablo's fork of citra issue.

also btw someone is rewritting the Android frontend and it will include the Home Button ;)

**Comment by 2020loryx** [comment]
Ok thank you
