### ISSUE TITLE
Inazuma Eleven GO Shine shows incorrect background during dialogue that shows the speakers's 3D models

### ISSUE THREAD

**Issue by ZeroTwoOne021** [PabloMK7/citra#60]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

0c2f076

### Description of Issue

During dialogue that shows the speakers's 3d models, the game will show the first background that was used in this type of dialogue, since the game launched.
This bug only occurs when Internal Resolution is set to 2x or higher.
![Screenshot_20240407_050349_Citra](https://github.com/PabloMK7/citra/assets/41229405/edb7176d-00a1-40f4-87c0-2f91f32e1ec1)

### Expected Behavior

This is how the background is supposed to look (Internal Resolution is set to 1x)
![Screenshot_20240407_051305_Lemonade](https://github.com/PabloMK7/citra/assets/41229405/16206ed3-4166-4760-9742-2720cd196af0)

### Reproduction Steps

(1- make sure that Internal Resolution is set to 2x or higher.)
2- initiate any kind of dialogue that shows the speakers's 3d models.
3- initiate another one of this kind of dialogue (make sure it's in a different location). You will notice that the background is the same as the one in step 2.

In this save file, speaking with any of the characters in the room will initiate this kind of dialogue.
[0006d400.zip](https://github.com/PabloMK7/citra/files/14895566/0006d400.zip)

### Log File

[citra_log.txt.old.txt](https://github.com/PabloMK7/citra/files/14895567/citra_log.txt.old.txt)

### System Configuration

CPU: Exynos 2400
GPU/Driver: Xclipse 940
RAM: 12GB
OS: Android 14

**Comment by GPUCode** [comment]
This should be fixed by https://github.com/PabloMK7/citra/pull/69
