### ISSUE TITLE
Easy way/guide to enable Pretendo

### ISSUE THREAD

**Issue by jih9uhuuh9** [PabloMK7/citra#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

There should be a way to toggle Pretendo in the UI, because Nintendo Network is gone, and there should be a UI setting for Pretendo, or a guide on how to setup Pretendo.

### Why would this feature be useful?

This would be useful, because this fork is mainly centered around online play, and with Nintendo Network gone, there would be an easy way for users to play online with Pretendo if there is a guide/UI option for it

**Comment by PabloMK7** [comment]
Hello, there are no plans to provide guides currently.
