### ISSUE TITLE
Some network connection issues during playing pokemon

### ISSUE THREAD

**Issue by liketolike** [PabloMK7/citra#7]
Currently playing X and OR,I will test USUM after a while
1.Cannot free battle in Battle Spot,Prompt:No data found on the server, please try again later.
2.I couldn't find each other on the passerby list using 3DS and emulator. I traded through GTS to make it appear on the list of acquaintances,
and can't battle, but can trade.
3.Wonder trading may experience a soft lock when discovering a trading partner, but after restarting the emulator, it is discovered that the transaction is complete,attach log.

**Comment by liketolike** [comment]
[citra_log.txt.old.txt](https://github.com/PabloMK7/citra/files/13352559/citra_log.txt.old.txt)

**Comment by Justin-ojay** [comment]
I have a sysnand.bin file from a 3ds XL in my android files , does anyone know how to extract the console unique codes from it

**Comment by PabloMK7** [comment]
This is caused by missing BOSS, will be fixed in the next release

**Comment by Justin-ojay** [comment]
How do I connect online on the 3ds home menu

**Comment by liketolike** [comment]
> This is caused by missing BOSS, will be fixed in the next release
I'm looking forward to it

**Comment by liketolike** [comment]
> How do I connect online on the 3ds home menu

I followed the installation instructions and he worked very well

**Comment by PabloMK7** [comment]
Fixed
