### ISSUE TITLE
Temperatura al máximo 

### ISSUE THREAD

**Issue by Muhzta** [PabloMK7/citra#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android

### Description of Issue

En menos de 30 min de juego el teléfono estaba para freír un huevo encima, avisándome hasta el propio teléfono de la alta temperatura.

### Expected Behavior

 A ver si ahora después de la que habéis liado todos los programadores de 3ds vais a hacer una buena chapuza con nuestros dispositivos. Porque con los otros emuladores puedo jugar horas sin problema 

### Reproduction Steps

.

### Log File

.

### System Configuration

Oneplus nord 3 5g

**Comment by PabloMK7** [comment]
xd

**Comment by Muhzta** [comment]
Encima me borras el issue, eres un crio seguramente con un poco de conocimiento informático. Espabila y arregla tu emulador y deja de meter mierda en vez de apoyaros y trabajar juntos todos, pero seguramente tu ego no te lo permita.

Y si, lo de la temperatura va en serio, así que algo no estarás haciendo bien cuando en los otros emuladores no pasa eso.

________________________________
De: PabloMK7 ***@***.***>
Enviado: domingo, 14 de abril de 2024 12:01
Para: PabloMK7/citra ***@***.***>
Cc: Muhzta ***@***.***>; Author ***@***.***>
Asunto: Re: [PabloMK7/citra] Temperatura al máximo (Issue #76)


xd
