### ISSUE TITLE
Conflict between LLE modules when opening Friends list

### ISSUE THREAD

**Issue by TwistedTempest** [PabloMK7/citra#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Source (Windows, MSVC)

### Description of Issue

When attempting to view the Friends list from the home menu with Pretendo IPS patches in place, the emulation hangs. This only occurs, however, if both the FRD and HTTP LLE modules are active; leaving only one or the other on fails to generate a friend code but otherwise does nothing. Additionally, without the Pretendo patch for TitleID 0004013000002902 the system throws an error code 001-0803 and refuses to connect.

Although others have been able to connect to Pretendo and create a valid friend code with Citra, this renders it functionally impossible to do so since (among others) the two listed LLE modules are necessary to establish an online connection (according to the archived 2.1 release)

### Expected Behavior

Attempting to visit the Friends list with patches in place to connect to Pretendo Network and LLE modules enabled causes emulation to hang at 0FPS until stopped

### Reproduction Steps

1. Copy Pretendo patches to 'mods' folder and select Pretendo network using Nimbus
2. Enable LLE patches FRD and HTTP
3. Ensure a valid Mii is present
4. Open Friends list after booting home menu

### Log File

[citra_log.txt.old.txt](https://github.com/PabloMK7/citra/files/14985157/citra_log.txt.old.txt)

### System Configuration

CPU: AMD Ryzen 7 3800X
GPU/Driver: RTX 3060 Ti / 552.12
RAM: 32GB 3200Mhz
OS: Windows 10

**Comment by PabloMK7** [comment]
Bug in pretendo patches: https://github.com/PretendoNetwork/nimbus/issues/39
