### ISSUE TITLE
Vulkan Crash in certain sceens of some games

### ISSUE THREAD

**Issue by FredericVincent0** [PabloMK7/citra#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

N/A

### Description of Issue

Vulkan Crash in certain sceens of some games

### Expected Behavior

Vulkan not Crash in certain sceens of some games

### Reproduction Steps

play some games with vulkan backend

### Log File

[citra_log.txt](https://github.com/PabloMK7/citra/files/14996921/citra_log.txt)

### System Configuration

CPU:Ryzen 5
GPU/Driver:Nvidia GeForce RTX 2060
RAM:16GB
OS:Windows 11

**Comment by Miguel-hrvs** [comment]
What more apart from donkey kong country returns 3d? Test this build: https://github.com/rtiangha/bravely-offline-citra/actions/runs/8680905595

**Comment by FredericVincent0** [comment]
Thanks, I'll check it out!

**Comment by Miguel-hrvs** [comment]
Are you using custom textures?

**Comment by FredericVincent0** [comment]
No

**Comment by FredericVincent0** [comment]
the build crash with any games load

**Comment by FredericVincent0** [comment]
but the previous build work without crash

**Comment by rtiangha** [comment]
This is just a shot in the dark, but does it still crash when you have Custom Textures unchecked in the settings?

**Comment by FredericVincent0** [comment]
It changing noting but I test the last build and no crash with vulkan

Le jeu. 18 avr. 2024, 00 h 16, Reg Tiangha ***@***.***> a
écrit :

**Comment by PabloMK7** [comment]
Closing as this is not specific enough.
