### ISSUE TITLE
The ACT module enabled causes citra to say a fatal error occured (i could reproduce on windows, linux arm64, and linux x86_64, macos too)

### ISSUE THREAD

**Issue by jih9uhuuh9** [PabloMK7/citra#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

e26ceab, r0c2f076

### Description of Issue

When trying to launch any app, with any LLE module enabled except ACT, it doesnt say fatal error, but if i enable ACT, Citra says fatal error, how to get it, cuz u need ACT for Pretendo, and how to setup the patches/modules for Pretendo?
[citra_log.txt](https://github.com/PabloMK7/citra/files/15048982/citra_log.txt)

### Expected Behavior

It is supposed to not throw fatal error with the ACT module enabled or not.

### Reproduction Steps

Setup keys, download home menu, provide console data, and enable ACT, there you go, fatal error.

### Log File

[citra_log.txt](https://github.com/PabloMK7/citra/files/15048987/citra_log.txt)

### System Configuration

CPU: Apple M1/Intel i7 on Windows PC
RAM: 16GB
OS: Linux, Windows, MacOS

**Comment by PabloMK7** [comment]
Make sure to download new 3ds titles AND old 3ds titles.

**Comment by chloebrahh** [comment]
I am unable to download Citra on my windows PC, is there something wrong with the link ? or, do i have a firewall i need to pull down ??
