### ISSUE TITLE
How to setup the Pretendo IPS patches/acc manager (mine arent working, no game works, and pnid linking crashes citra), but only the pretendo eula is visble in nnid settings

### ISSUE THREAD

**Issue by jih9uhuuh9** [PabloMK7/citra#84]
### Issue

I need help, i have the 5 LLE modules needed (HTTP, SSL, BOSS, FRD, ACT) enabled, but i try to connect to pretendo on mk7 and it says connecting forever, and if i try to link a pnid, it crashes, how to get juxt, pnids, and games working? is my file structure wrong or what, cuz i see the pretendo eula in nnid settings, but thats about it?, here is the load/mods tree, /home/sus/.local/share/citra-emu/load i have n3ds and o3ds titles too
└── mods
    ├── 000400300000BC02
    │   └── code.ips
    ├── 000400300000BD02
    │   └── code.ips
    ├── 000400300000BE02
    │   └── code.ips
    ├── 0004013000002902
    │   └── code.ips
    ├── 0004013000002E02
    │   └── code.ips
    ├── 0004013000002F02
    │   └── code.ips
    ├── 0004013000003202
    │   └── code.ips
    └── 0004013000003802
        └── code.ips
and the virtual sd tree,
[vsdtree.txt](https://github.com/PabloMK7/citra/files/15052024/vsdtree.txt), and the virtual nand tree, 
[nand_tree.txt](https://github.com/PabloMK7/citra/files/15052027/nand_tree.txt), and log files, 
[citra_log.txt](https://github.com/PabloMK7/citra/files/15052028/citra_log.txt)
[citra_log.txt.old.txt](https://github.com/PabloMK7/citra/files/15052029/citra_log.txt.old.txt)

**Comment by Linkdash2019** [comment]
Disable HTTP
