### ISSUE TITLE
fire emblem fates crash in the lastest version

### ISSUE THREAD

**Issue by zqisme** [PabloMK7/citra#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

ra8e601a

### Description of Issue

open the game, don't push any button then game will show the classes,  when the dark princess come out citra will crash
maybe caused by https://github.com/PabloMK7/citra/pull/77
has the same issue in the final citra nightly

https://github.com/PabloMK7/citra/assets/61244668/9195e232-ae77-42d5-934f-9d11d7de8993

### Expected Behavior

don't crash

### Reproduction Steps

open the game, don't push any button then game will show the classes,  when the dark princess come out citra will crash

### Log File

[citra_log.txt](https://github.com/PabloMK7/citra/files/15071969/citra_log.txt)

### System Configuration

CPU:
GPU/Driver:1660s
RAM:
OS:windows 10

**Comment by PabloMK7** [comment]
From the logs you seem to have custom textures, can you try disabling that.

**Comment by zqisme** [comment]
> From the logs you seem to have custom textures, can you try disabling that.

I disable the custom textures, still crash
[citra_log.txt.old.txt](https://github.com/PabloMK7/citra/files/15075629/citra_log.txt.old.txt)

**Comment by zqisme** [comment]
> `[ 2.169574] Service.FS <Info> core\file_sys\layered_fs.cpp:FileSys::LayeredFS::LoadRelocations::<lambda_1>::operator ():176: LayeredFS created file /bu/uDres_F_kgt0_upp1_0_cl0n_Effie.bch.lz [ 2.169706] Service.FS <Info> core\file_sys\layered_fs.cpp:FileSys::LayeredFS::LoadRelocations::<lambda_1>::operator ():183: LayeredFS replacement file in use for /bu/uDres_F_kgt0_upp1_0_cl0n_Effie.bch.lz [ 2.169755] Service.FS <Info> core\file_sys\layered_fs.cpp:FileSys::LayeredFS::LoadRelocations::<lambda_1>::operator ():176: LayeredFS created file /bu/uDres_F_kgt0_upp3_0_cl0n_Caeldori.bch.lz` Do you have mods enabled? Try disabling them

okay
[citra_log.txt](https://github.com/PabloMK7/citra/files/15104313/citra_log.txt)

**Comment by keisa39** [comment]
It's the Sword Ganglari model you receive in chapter 2 that causes the crash. It's also the default sword of dark princess on the screen menu, thus causing the crash.

There is an option to receive the sword later ingame, which also causes the crash when you zoom into it.

**Comment by Hekel1989** [comment]
> It's the Sword Ganglari model you receive in chapter 2 that causes the crash. It's also the default sword of dark princess on the screen menu, thus causing the crash.
> 
> 
> 
> There is an option to receive the sword later ingame, which also causes the crash when you zoom into it.
> 
> 
> 
> Right now the last nightly build is the only working build at the moment, other forks (like Lime3DS) also crashes when the sword appears ingame.

Would you happen to know which version?
I've tried the last available on this repo, and I get the same crash exactly on the spots you mentioned

**Comment by TheMet309** [comment]
I'm sorry if the English is bad, because I say this with a translator, but I tried with citra nightly 2095 and it didn't give me any crashes

**Comment by PabloMK7** [comment]
> It's the Sword Ganglari model you receive in chapter 2 that causes the crash. It's also the default sword of dark princess on the screen menu, thus causing the crash.
> 
> There is an option to receive the sword later ingame, which also causes the crash when you zoom into it.
> 
> Right now the last nightly build is the only working build at the moment, other forks (like Lime3DS) also crashes when the sword appears ingame.

Can you provide a save file and steps to reproduce?

**Comment by zqisme** [comment]
> > It's the Sword Ganglari model you receive in chapter 2 that causes the crash. It's also the default sword of dark princess on the screen menu, thus causing the crash.
> > There is an option to receive the sword later ingame, which also causes the crash when you zoom into it.
> > Right now the last nightly build is the only working build at the moment, other forks (like Lime3DS) also crashes when the sword appears ingame.
> 
> Can you provide a save file and steps to reproduce?

Fixed in the latest version
