### ISSUE TITLE
Citra running into a fatal error when launching Youkai Watch 3 Tempura.

### ISSUE THREAD

**Issue by squarepizza1** [PabloMK7/citra#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

ra8e601a

### Description of Issue

Youkai Watch 3 Tempura gives a fatal error when launched. The game seems to work fine though.

### Expected Behavior

The game should launch without a fatal error.

### Reproduction Steps

Just boot the game.

### Log File

[citra_log.txt](https://github.com/PabloMK7/citra/files/15124647/citra_log.txt)

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by squarepizza1** [comment]
Turns out my dump was bad. Redumping the game fixed the issue.

**Comment by squarepizza1** [comment]
The Glitch started happening again. If I load it on my Steam Deck with Citra 2104, it works without a fatal error.

**Comment by PabloMK7** [comment]
You have LLE modules enabled but didn't dump the CTCert

**Comment by squarepizza1** [comment]
How do I dump the CTCert log?
