### ISSUE TITLE
What is the current minimum requirements for Vulkan Support?

### ISSUE THREAD

**Issue by rtiangha** [PabloMK7/citra#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

HEAD

### Description of Issue

Some people are reporting various issues with Vulkan, and I was curious what the minimum supported Vulkan version is right now. After researching on my own, I know that Vulkan support debuted at 1.1. Then commit fa08df21a50f7de06f39333bd441d2f44c9f7ed8 on Nov 10, 2023 hardcoded it at 1.3, and then on Feb 15, 2024, it was changed back (I think?) to 1.1 with commit aa6809e2a8f8264f6c5ed359a0fc458c66368856 .

I feel like perhaps those who are complaining of issues more have video card support older than 1.3, so I'm just curious as to what the current system requirements are since a lot of the documentation and FAQs have been lost since the shutdown.

Some people have talked about having more success with older versions prior to Nov 10 (so Nightly 2030) but no success with modern versions (even after Feb 15) which is why I became curious about the minimal requirements.

### Expected Behavior

Ideally, Vulkan works correctly for all supported hardware.

### Reproduction Steps

N/A

### Log File

N/A

### System Configuration

N/A

**Comment by Miguel-hrvs** [comment]
I'll test with my laptop's hd5500 which is one the first intel gpu's with vulkan 1.1 support.

**Comment by mrcmunir** [comment]
Vulkan 1.1 support but needed recommeded  supporting these physical features 
https://github.com/PabloMK7/citra/blob/b5126f979ca31e6f6519c70788da8c25a2cdf7d7/src/video_core/renderer_vulkan/vk_instance.cpp#L513
